-- ========================================================
-- Dreamcoder Light — generated by Dreamcoder sync
-- ========================================================
-- Loaded by the dreamcoder dispatcher (colors/dreamcoder.lua).
-- Can also be loaded directly: vim.cmd.colorscheme("dreamcoder-light")
-- ========================================================

vim.g.colors_name = "dreamcoder-light"

local c = {
  bg        = "#f3eadc",
  surface0  = "#fff7ea",
  surface1  = "#decbb1",
  surface2  = "#c8ad89",
  text      = "#17120d",
  muted     = "#352e22",
  subtle    = "#554638",
  comment   = "#725e4c",
  accent    = "#824f16",
  accent2   = "#a7471c",
  diagnostic = "#0d4a68",
  sage      = "#3d723d",
  lavender  = "#57478b",
  mauve     = "#7d3e64",
  error     = "#842f24",
  warning   = "#654300",
  border    = "#8a7358",
  border_ui = "#66513b",
  selection = "#decbb1",
}

local function h(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end

-- ── Editor UI ────────────────────────────────────────────────
-- Normal background is opaque in light so dark terminal transparency cannot hide text.
-- Dark mode keeps transparent Normal for Anthracite Steel glass.

  vim.api.nvim_set_hl(0, "Normal", {
    fg = "#17120d",
    bg = "#f3eadc"
  })

  vim.api.nvim_set_hl(0, "NormalFloat", {
    fg = "#17120d",
    bg = "#fff7ea"
  })

  vim.api.nvim_set_hl(0, "FloatBorder", {
    fg = "#66513b",
    bg = "#fff7ea"
  })

  vim.api.nvim_set_hl(0, "FloatTitle", {
    fg = "#824f16",
    bold = true
  })

  vim.api.nvim_set_hl(0, "NonText", {
    fg = "#554638"
  })

  vim.api.nvim_set_hl(0, "SpecialKey", {
    fg = "#352e22"
  })

  vim.api.nvim_set_hl(0, "Whitespace", {
    fg = "#66513b"
  })

  vim.api.nvim_set_hl(0, "EndOfBuffer", {
    fg = "none"
  })

  vim.api.nvim_set_hl(0, "Cursor", {
    fg = "#f3eadc",
    bg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "lCursor", {
    fg = "#f3eadc",
    bg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "CursorLine", {
    bg = "#fff7ea"
  })

  vim.api.nvim_set_hl(0, "CursorLineNr", {
    fg = "#824f16",
    bold = true
  })

  vim.api.nvim_set_hl(0, "LineNr", {
    fg = "#352e22"
  })

  vim.api.nvim_set_hl(0, "CursorColumn", {
    bg = "#fff7ea"
  })

  vim.api.nvim_set_hl(0, "ColorColumn", {
    bg = "#fff7ea"
  })

  vim.api.nvim_set_hl(0, "SignColumn", {
    bg = "#f3eadc"
  })


  -- ── Selection & Search ───────────────────────────────
  vim.api.nvim_set_hl(0, "Visual", {
    fg = "#17120d",
    bg = "#decbb1"
  })

  vim.api.nvim_set_hl(0, "VisualNOS", {
    fg = "#17120d",
    bg = "#decbb1"
  })

  vim.api.nvim_set_hl(0, "Search", {
    fg = "#f3eadc",
    bg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "IncSearch", {
    fg = "#f3eadc",
    bg = "#a7471c"
  })

  vim.api.nvim_set_hl(0, "CurSearch", {
    fg = "#f3eadc",
    bg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "Substitute", {
    fg = "#f3eadc",
    bg = "#a7471c"
  })

  vim.api.nvim_set_hl(0, "MatchParen", {
    fg = "#a7471c",
    bold = true
  })


  -- ── Popup Menu ────────────────────────────────────────
  vim.api.nvim_set_hl(0, "Pmenu", {
    fg = "#352e22",
    bg = "#decbb1"
  })

  vim.api.nvim_set_hl(0, "PmenuSel", {
    fg = "#f3eadc",
    bg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "PmenuSbar", {
    bg = "#c8ad89"
  })

  vim.api.nvim_set_hl(0, "PmenuThumb", {
    bg = "#352e22"
  })


  -- ── Statusline & Winbar ───────────────────────────────
  vim.api.nvim_set_hl(0, "StatusLine", {
    fg = "#17120d",
    bg = "#decbb1"
  })

  vim.api.nvim_set_hl(0, "StatusLineNC", {
    fg = "#352e22",
    bg = "#fff7ea"
  })

  vim.api.nvim_set_hl(0, "StatusLineTerm", {
    fg = "#17120d",
    bg = "#decbb1"
  })

  vim.api.nvim_set_hl(0, "StatusLineTermNC", {
    fg = "#352e22",
    bg = "#fff7ea"
  })

  vim.api.nvim_set_hl(0, "WinBar", {
    fg = "#17120d",
    bg = "#decbb1"
  })

  vim.api.nvim_set_hl(0, "WinBarNC", {
    fg = "#352e22",
    bg = "#fff7ea"
  })

  vim.api.nvim_set_hl(0, "WinSeparator", {
    fg = "#66513b"
  })


  -- ── Tabline ────────────────────────────────────────────
  vim.api.nvim_set_hl(0, "TabLine", {
    fg = "#352e22",
    bg = "#fff7ea"
  })

  vim.api.nvim_set_hl(0, "TabLineSel", {
    fg = "#17120d",
    bg = "#decbb1"
  })

  vim.api.nvim_set_hl(0, "TabLineFill", {
    bg = "#f3eadc"
  })


  -- ── Folds ─────────────────────────────────────────────
  vim.api.nvim_set_hl(0, "Folded", {
    fg = "#352e22",
    bg = "#fff7ea"
  })

  vim.api.nvim_set_hl(0, "FoldColumn", {
    fg = "#352e22"
  })


  -- ── Diff ──────────────────────────────────────────────
  vim.api.nvim_set_hl(0, "DiffAdd", {
    bg = "#c5cfb6"
  })

  vim.api.nvim_set_hl(0, "DiffChange", {
    bg = "#d1c1a4"
  })

  vim.api.nvim_set_hl(0, "DiffDelete", {
    bg = "#dabbaf"
  })

  vim.api.nvim_set_hl(0, "DiffText", {
    bg = "#abc4bf"
  })


  -- ── Spell ─────────────────────────────────────────────
  vim.api.nvim_set_hl(0, "SpellBad", {
    sp = "#842f24",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "SpellCap", {
    sp = "#654300",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "SpellLocal", {
    sp = "#0d4a68",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "SpellRare", {
    sp = "#7d3e64",
    undercurl = true
  })


  -- ── Messages ──────────────────────────────────────────
  vim.api.nvim_set_hl(0, "MsgArea", {
    fg = "#17120d"
  })

  vim.api.nvim_set_hl(0, "ModeMsg", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "WarningMsg", {
    fg = "#654300"
  })

  vim.api.nvim_set_hl(0, "ErrorMsg", {
    fg = "#842f24"
  })

  vim.api.nvim_set_hl(0, "Question", {
    fg = "#0d4a68"
  })


  -- ── Misc ──────────────────────────────────────────────
  vim.api.nvim_set_hl(0, "Title", {
    fg = "#824f16",
    bold = true
  })

  vim.api.nvim_set_hl(0, "Directory", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "Conceal", {
    fg = "#352e22"
  })

  vim.api.nvim_set_hl(0, "TermCursor", {
    fg = "#f3eadc",
    bg = "#824f16"
  })


  -- ── Classic Syntax ────────────────────────────────────
  vim.api.nvim_set_hl(0, "Comment", {
    fg = "#725e4c",
    italic = true
  })

  vim.api.nvim_set_hl(0, "Constant", {
    fg = "#7d3e64"
  })

  vim.api.nvim_set_hl(0, "String", {
    fg = "#3d723d"
  })

  vim.api.nvim_set_hl(0, "Character", {
    fg = "#3d723d"
  })

  vim.api.nvim_set_hl(0, "Number", {
    fg = "#7d3e64"
  })

  vim.api.nvim_set_hl(0, "Boolean", {
    fg = "#57478b"
  })

  vim.api.nvim_set_hl(0, "Float", {
    fg = "#7d3e64"
  })

  vim.api.nvim_set_hl(0, "Identifier", {
    fg = "#352e22"
  })

  vim.api.nvim_set_hl(0, "Function", {
    fg = "#a7471c"
  })

  vim.api.nvim_set_hl(0, "Statement", {
    fg = "#824f16",
    bold = true
  })

  vim.api.nvim_set_hl(0, "Conditional", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "Repeat", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "Label", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "Operator", {
    fg = "#a7471c"
  })

  vim.api.nvim_set_hl(0, "Keyword", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "Exception", {
    fg = "#842f24"
  })

  vim.api.nvim_set_hl(0, "PreProc", {
    fg = "#554638"
  })

  vim.api.nvim_set_hl(0, "Include", {
    fg = "#554638"
  })

  vim.api.nvim_set_hl(0, "Define", {
    fg = "#554638"
  })

  vim.api.nvim_set_hl(0, "PreCondit", {
    fg = "#554638"
  })

  vim.api.nvim_set_hl(0, "Type", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "StorageClass", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "Structure", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "Typedef", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "Special", {
    fg = "#57478b"
  })

  vim.api.nvim_set_hl(0, "SpecialChar", {
    fg = "#57478b"
  })

  vim.api.nvim_set_hl(0, "Delimiter", {
    fg = "#352e22"
  })

  vim.api.nvim_set_hl(0, "SpecialComment", {
    fg = "#725e4c"
  })

  vim.api.nvim_set_hl(0, "Debug", {
    fg = "#654300"
  })

  vim.api.nvim_set_hl(0, "Underlined", {
    fg = "#0d4a68",
    underline = true
  })

  vim.api.nvim_set_hl(0, "Ignore", {
    fg = "#f3eadc"
  })

  vim.api.nvim_set_hl(0, "Error", {
    fg = "#842f24"
  })

  vim.api.nvim_set_hl(0, "Todo", {
    fg = "#654300",
    bold = true
  })


  -- ── Treesitter ────────────────────────────────────────
  vim.api.nvim_set_hl(0, "@variable", {
    fg = "#352e22"
  })

  vim.api.nvim_set_hl(0, "@variable.builtin", {
    fg = "#57478b"
  })

  vim.api.nvim_set_hl(0, "@variable.parameter", {
    fg = "#7d3e64"
  })

  vim.api.nvim_set_hl(0, "@variable.member", {
    fg = "#352e22"
  })

  vim.api.nvim_set_hl(0, "@constant", {
    fg = "#7d3e64"
  })

  vim.api.nvim_set_hl(0, "@constant.builtin", {
    fg = "#57478b"
  })

  vim.api.nvim_set_hl(0, "@constant.macro", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "@module", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "@module.builtin", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "@label", {
    fg = "#a7471c"
  })

  vim.api.nvim_set_hl(0, "@string", {
    fg = "#3d723d"
  })

  vim.api.nvim_set_hl(0, "@string.documentation", {
    fg = "#3d723d",
    italic = true
  })

  vim.api.nvim_set_hl(0, "@string.regex", {
    fg = "#654300"
  })

  vim.api.nvim_set_hl(0, "@string.escape", {
    fg = "#654300"
  })

  vim.api.nvim_set_hl(0, "@character", {
    fg = "#3d723d"
  })

  vim.api.nvim_set_hl(0, "@character.special", {
    fg = "#57478b"
  })

  vim.api.nvim_set_hl(0, "@number", {
    fg = "#7d3e64"
  })

  vim.api.nvim_set_hl(0, "@boolean", {
    fg = "#57478b"
  })

  vim.api.nvim_set_hl(0, "@float", {
    fg = "#7d3e64"
  })

  vim.api.nvim_set_hl(0, "@function", {
    fg = "#a7471c"
  })

  vim.api.nvim_set_hl(0, "@function.builtin", {
    fg = "#a7471c",
    bold = true
  })

  vim.api.nvim_set_hl(0, "@function.call", {
    fg = "#a7471c"
  })

  vim.api.nvim_set_hl(0, "@function.macro", {
    fg = "#a7471c"
  })

  vim.api.nvim_set_hl(0, "@function.method", {
    fg = "#a7471c"
  })

  vim.api.nvim_set_hl(0, "@function.method.call", {
    fg = "#a7471c"
  })

  vim.api.nvim_set_hl(0, "@parameter", {
    fg = "#7d3e64"
  })

  vim.api.nvim_set_hl(0, "@method", {
    fg = "#a7471c"
  })

  vim.api.nvim_set_hl(0, "@field", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "@property", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "@constructor", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "@conditional", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "@repeat", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "@debug", {
    fg = "#654300"
  })

  vim.api.nvim_set_hl(0, "@include", {
    fg = "#554638"
  })

  vim.api.nvim_set_hl(0, "@operator", {
    fg = "#a7471c"
  })

  vim.api.nvim_set_hl(0, "@keyword", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "@keyword.function", {
    fg = "#824f16",
    italic = true
  })

  vim.api.nvim_set_hl(0, "@keyword.operator", {
    fg = "#a7471c"
  })

  vim.api.nvim_set_hl(0, "@keyword.return", {
    fg = "#824f16",
    bold = true
  })

  vim.api.nvim_set_hl(0, "@exception", {
    fg = "#842f24"
  })

  vim.api.nvim_set_hl(0, "@type", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "@type.builtin", {
    fg = "#0d4a68",
    bold = true
  })

  vim.api.nvim_set_hl(0, "@type.definition", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "@type.qualifier", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "@storageclass", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "@attribute", {
    fg = "#554638"
  })

  vim.api.nvim_set_hl(0, "@symbol", {
    fg = "#57478b"
  })

  vim.api.nvim_set_hl(0, "@punctuation.delimiter", {
    fg = "#352e22"
  })

  vim.api.nvim_set_hl(0, "@punctuation.bracket", {
    fg = "#352e22"
  })

  vim.api.nvim_set_hl(0, "@punctuation.special", {
    fg = "#57478b"
  })

  vim.api.nvim_set_hl(0, "@comment", {
    fg = "#725e4c",
    italic = true
  })

  vim.api.nvim_set_hl(0, "@comment.error", {
    fg = "#842f24"
  })

  vim.api.nvim_set_hl(0, "@comment.warning", {
    fg = "#654300"
  })

  vim.api.nvim_set_hl(0, "@comment.todo", {
    fg = "#654300",
    bold = true
  })

  vim.api.nvim_set_hl(0, "@comment.note", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "@markup.strong", {
    bold = true
  })

  vim.api.nvim_set_hl(0, "@markup.italic", {
    italic = true
  })

  vim.api.nvim_set_hl(0, "@markup.strikethrough", {
    strikethrough = true
  })

  vim.api.nvim_set_hl(0, "@markup.underline", {
    underline = true
  })

  vim.api.nvim_set_hl(0, "@markup.heading", {
    fg = "#824f16",
    bold = true
  })

  vim.api.nvim_set_hl(0, "@markup.quote", {
    fg = "#725e4c",
    italic = true
  })

  vim.api.nvim_set_hl(0, "@markup.math", {
    fg = "#57478b"
  })

  vim.api.nvim_set_hl(0, "@markup.link", {
    fg = "#824f16",
    underline = true
  })

  vim.api.nvim_set_hl(0, "@markup.link.label", {
    fg = "#824f16",
    underline = true
  })

  vim.api.nvim_set_hl(0, "@markup.link.url", {
    fg = "#a7471c",
    underline = true
  })

  vim.api.nvim_set_hl(0, "@markup.raw", {
    fg = "#3d723d"
  })

  vim.api.nvim_set_hl(0, "@markup.list", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "@diff.plus", {
    fg = "#3d723d"
  })

  vim.api.nvim_set_hl(0, "@diff.minus", {
    fg = "#842f24"
  })

  vim.api.nvim_set_hl(0, "@diff.delta", {
    fg = "#654300"
  })

  vim.api.nvim_set_hl(0, "@tag", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "@tag.attribute", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "@tag.delimiter", {
    fg = "#352e22"
  })


  -- ── LSP / Diagnostics ────────────────────────────────
  vim.api.nvim_set_hl(0, "DiagnosticError", {
    fg = "#842f24"
  })

  vim.api.nvim_set_hl(0, "DiagnosticWarn", {
    fg = "#654300"
  })

  vim.api.nvim_set_hl(0, "DiagnosticInfo", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "DiagnosticHint", {
    fg = "#57478b"
  })

  vim.api.nvim_set_hl(0, "DiagnosticOk", {
    fg = "#3d723d"
  })

  vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", {
    sp = "#842f24",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", {
    sp = "#654300",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", {
    sp = "#0d4a68",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", {
    sp = "#57478b",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", {
    fg = "#842f24"
  })

  vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", {
    fg = "#654300"
  })

  vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", {
    fg = "#57478b"
  })

  vim.api.nvim_set_hl(0, "DiagnosticFloatingError", {
    fg = "#842f24"
  })

  vim.api.nvim_set_hl(0, "DiagnosticFloatingWarn", {
    fg = "#654300"
  })

  vim.api.nvim_set_hl(0, "DiagnosticFloatingInfo", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "DiagnosticFloatingHint", {
    fg = "#57478b"
  })

  vim.api.nvim_set_hl(0, "DiagnosticSignError", {
    fg = "#842f24"
  })

  vim.api.nvim_set_hl(0, "DiagnosticSignWarn", {
    fg = "#654300"
  })

  vim.api.nvim_set_hl(0, "DiagnosticSignInfo", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "DiagnosticSignHint", {
    fg = "#57478b"
  })

  vim.api.nvim_set_hl(0, "LspReferenceText", {
    bg = "#decbb1"
  })

  vim.api.nvim_set_hl(0, "LspReferenceRead", {
    bg = "#decbb1"
  })

  vim.api.nvim_set_hl(0, "LspReferenceWrite", {
    bg = "#decbb1"
  })

  vim.api.nvim_set_hl(0, "LspInlayHint", {
    fg = "#725e4c",
    bg = "#fff7ea"
  })


  -- ── Telescope ─────────────────────────────────────────
  vim.api.nvim_set_hl(0, "TelescopeNormal", {
    fg = "#17120d",
    bg = "#f3eadc"
  })

  vim.api.nvim_set_hl(0, "TelescopeBorder", {
    fg = "#66513b",
    bg = "#f3eadc"
  })

  vim.api.nvim_set_hl(0, "TelescopeTitle", {
    fg = "#824f16",
    bold = true
  })

  vim.api.nvim_set_hl(0, "TelescopePromptNormal", {
    fg = "#17120d",
    bg = "#fff7ea"
  })

  vim.api.nvim_set_hl(0, "TelescopePromptBorder", {
    fg = "#66513b",
    bg = "#fff7ea"
  })

  vim.api.nvim_set_hl(0, "TelescopePromptTitle", {
    fg = "#a7471c",
    bold = true
  })

  vim.api.nvim_set_hl(0, "TelescopeSelection", {
    fg = "#17120d",
    bg = "#decbb1"
  })

  vim.api.nvim_set_hl(0, "TelescopeMultiSelection", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "TelescopeMatching", {
    fg = "#824f16",
    bold = true
  })

  vim.api.nvim_set_hl(0, "TelescopePreviewNormal", {
    fg = "#17120d",
    bg = "#fff7ea"
  })

  vim.api.nvim_set_hl(0, "TelescopePreviewBorder", {
    fg = "#66513b",
    bg = "#fff7ea"
  })

  vim.api.nvim_set_hl(0, "TelescopeResultsNormal", {
    fg = "#17120d",
    bg = "#f3eadc"
  })

  vim.api.nvim_set_hl(0, "TelescopeResultsBorder", {
    fg = "#66513b",
    bg = "#f3eadc"
  })


  -- ── NvimTree ─────────────────────────────────────────
  vim.api.nvim_set_hl(0, "NvimTreeNormal", {
    fg = "#17120d",
    bg = "#f3eadc"
  })

  vim.api.nvim_set_hl(0, "NvimTreeRootFolder", {
    fg = "#824f16",
    bold = true
  })

  vim.api.nvim_set_hl(0, "NvimTreeGitDirty", {
    fg = "#654300"
  })

  vim.api.nvim_set_hl(0, "NvimTreeGitNew", {
    fg = "#3d723d"
  })

  vim.api.nvim_set_hl(0, "NvimTreeGitDeleted", {
    fg = "#842f24"
  })

  vim.api.nvim_set_hl(0, "NvimTreeOpenedFile", {
    fg = "#a7471c"
  })

  vim.api.nvim_set_hl(0, "NvimTreeSpecialFile", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "NvimTreeSymlink", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "NvimTreeFolderName", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "NvimTreeFolderIcon", {
    fg = "#352e22"
  })

  vim.api.nvim_set_hl(0, "NvimTreeEmptyFolderName", {
    fg = "#352e22"
  })

  vim.api.nvim_set_hl(0, "NvimTreeOpenedFolderName", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "NvimTreeImageFile", {
    fg = "#57478b"
  })

  vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", {
    fg = "#66513b"
  })

  vim.api.nvim_set_hl(0, "NvimTreeWinSeparator", {
    fg = "#66513b",
    bg = "#f3eadc"
  })

  vim.api.nvim_set_hl(0, "NvimTreeCursorLine", {
    bg = "#fff7ea"
  })


  -- ── WhichKey ─────────────────────────────────────────
  vim.api.nvim_set_hl(0, "WhichKey", {
    fg = "#824f16",
    bold = true
  })

  vim.api.nvim_set_hl(0, "WhichKeyGroup", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "WhichKeyDesc", {
    fg = "#17120d"
  })

  vim.api.nvim_set_hl(0, "WhichKeySeperator", {
    fg = "#352e22"
  })

  vim.api.nvim_set_hl(0, "WhichKeySeparator", {
    fg = "#352e22"
  })

  vim.api.nvim_set_hl(0, "WhichKeyFloat", {
    fg = "#17120d",
    bg = "#fff7ea"
  })

  vim.api.nvim_set_hl(0, "WhichKeyBorder", {
    fg = "#66513b"
  })

  vim.api.nvim_set_hl(0, "WhichKeyValue", {
    fg = "#7d3e64"
  })


  -- ── Lazy / Noice / Cmp ───────────────────────────────
  vim.api.nvim_set_hl(0, "LazyNormal", {
    fg = "#17120d",
    bg = "#f3eadc"
  })

  vim.api.nvim_set_hl(0, "LazyReasonPlugin", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "LazyReasonStart", {
    fg = "#3d723d"
  })

  vim.api.nvim_set_hl(0, "LazyReasonSource", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "LazyReasonRt", {
    fg = "#7d3e64"
  })

  vim.api.nvim_set_hl(0, "LazyReasonCmd", {
    fg = "#57478b"
  })

  vim.api.nvim_set_hl(0, "LazyValue", {
    fg = "#7d3e64"
  })

  vim.api.nvim_set_hl(0, "LazyCommit", {
    fg = "#3d723d"
  })

  vim.api.nvim_set_hl(0, "LazySpecial", {
    fg = "#57478b"
  })

  vim.api.nvim_set_hl(0, "LazyDir", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "LazyH1", {
    fg = "#824f16",
    bold = true
  })

  vim.api.nvim_set_hl(0, "LazyButton", {
    fg = "#17120d",
    bg = "#decbb1"
  })

  vim.api.nvim_set_hl(0, "LazyButtonActive", {
    fg = "#f3eadc",
    bg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "NoiceMsg", {
    fg = "#17120d"
  })

  vim.api.nvim_set_hl(0, "NoiceCursor", {
    fg = "#f3eadc",
    bg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "MiniCompletionActiveParameter", {
    underline = true
  })

  vim.api.nvim_set_hl(0, "CmpItemAbbr", {
    fg = "#17120d"
  })

  vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", {
    fg = "#824f16",
    bold = true
  })

  vim.api.nvim_set_hl(0, "CmpItemAbbrMatchFuzzy", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "CmpItemKind", {
    fg = "#352e22"
  })

  vim.api.nvim_set_hl(0, "CmpItemMenu", {
    fg = "#352e22"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindSnippet", {
    fg = "#7d3e64"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindKeyword", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindText", {
    fg = "#17120d"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindMethod", {
    fg = "#a7471c"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindFunction", {
    fg = "#a7471c"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindConstructor", {
    fg = "#824f16"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindField", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindVariable", {
    fg = "#7d3e64"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindClass", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindInterface", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindModule", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindProperty", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindUnit", {
    fg = "#3d723d"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindValue", {
    fg = "#7d3e64"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindEnum", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindEnumMember", {
    fg = "#7d3e64"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindColor", {
    fg = "#57478b"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindFile", {
    fg = "#17120d"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindReference", {
    fg = "#a7471c"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindFolder", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindEvent", {
    fg = "#654300"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindOperator", {
    fg = "#a7471c"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindTypeParameter", {
    fg = "#0d4a68"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindCopied", {
    fg = "#3d723d"
  })


  -- ── GitSigns ────────────────────────────────────────
  vim.api.nvim_set_hl(0, "GitSignsAdd", {
    fg = "#3d723d"
  })

  vim.api.nvim_set_hl(0, "GitSignsChange", {
    fg = "#654300"
  })

  vim.api.nvim_set_hl(0, "GitSignsDelete", {
    fg = "#842f24"
  })

  vim.api.nvim_set_hl(0, "GitSignsAddNr", {
    fg = "#3d723d"
  })

  vim.api.nvim_set_hl(0, "GitSignsChangeNr", {
    fg = "#654300"
  })

  vim.api.nvim_set_hl(0, "GitSignsDeleteNr", {
    fg = "#842f24"
  })

  vim.api.nvim_set_hl(0, "GitSignsAddLn", {
    bg = "#e4e0cf"
  })

  vim.api.nvim_set_hl(0, "GitSignsChangeLn", {
    bg = "#e8ddca"
  })

  vim.api.nvim_set_hl(0, "GitSignsDeleteLn", {
    bg = "#eadbcd"
  })

  vim.api.nvim_set_hl(0, "GitSignsCurrentLineBlame", {
    fg = "#352e22"
  })

