-- ========================================================
-- Dreamcoder Dark Black OLED Night — generated by Dreamcoder sync
-- ========================================================
-- Loaded by the dreamcoder dispatcher (colors/dreamcoder.lua).
-- Can also be loaded directly: vim.cmd.colorscheme("dreamcoder-night")
-- ========================================================

vim.g.colors_name = "dreamcoder-night"

local c = {
  bg        = "#000000",
  surface0  = "#050507",
  surface1  = "#0c0c0e",
  surface2  = "#141418",
  text      = "#bcc7d5",
  muted     = "#8a96a7",
  subtle    = "#8c94a4",
  comment   = "#a69ba6",
  accent    = "#a4afee",
  accent2   = "#9f8ce9",
  diagnostic = "#62b9e2",
  sage      = "#43b48b",
  lavender  = "#9f8ce9",
  mauve     = "#b98beb",
  error     = "#e88484",
  warning   = "#d1a126",
  border    = "#6d7788",
  border_ui = "#6d7788",
  selection = "#141418",
}

local function h(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end

-- ── Editor UI ────────────────────────────────────────────────
-- Normal background is opaque in light so dark terminal transparency cannot hide text.
-- Dark mode keeps transparent Normal for Anthracite Steel glass.

  vim.api.nvim_set_hl(0, "Normal", {
    fg = "#bcc7d5",
    bg = "none"
  })

  vim.api.nvim_set_hl(0, "NormalFloat", {
    fg = "#bcc7d5",
    bg = "#050507"
  })

  vim.api.nvim_set_hl(0, "FloatBorder", {
    fg = "#6d7788",
    bg = "#050507"
  })

  vim.api.nvim_set_hl(0, "FloatTitle", {
    fg = "#a4afee",
    bold = true
  })

  vim.api.nvim_set_hl(0, "NonText", {
    fg = "#8c94a4"
  })

  vim.api.nvim_set_hl(0, "SpecialKey", {
    fg = "#8a96a7"
  })

  vim.api.nvim_set_hl(0, "Whitespace", {
    fg = "#6d7788"
  })

  vim.api.nvim_set_hl(0, "EndOfBuffer", {
    fg = "none"
  })

  vim.api.nvim_set_hl(0, "Cursor", {
    fg = "#000000",
    bg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "lCursor", {
    fg = "#000000",
    bg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "CursorLine", {
    bg = "#050507"
  })

  vim.api.nvim_set_hl(0, "CursorLineNr", {
    fg = "#a4afee",
    bold = true
  })

  vim.api.nvim_set_hl(0, "LineNr", {
    fg = "#8a96a7"
  })

  vim.api.nvim_set_hl(0, "CursorColumn", {
    bg = "#050507"
  })

  vim.api.nvim_set_hl(0, "ColorColumn", {
    bg = "#050507"
  })

  vim.api.nvim_set_hl(0, "SignColumn", {
    bg = "none"
  })


  -- ── Selection & Search ───────────────────────────────
  vim.api.nvim_set_hl(0, "Visual", {
    fg = "#bcc7d5",
    bg = "#141418"
  })

  vim.api.nvim_set_hl(0, "VisualNOS", {
    fg = "#bcc7d5",
    bg = "#141418"
  })

  vim.api.nvim_set_hl(0, "Search", {
    fg = "#000000",
    bg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "IncSearch", {
    fg = "#000000",
    bg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "CurSearch", {
    fg = "#000000",
    bg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "Substitute", {
    fg = "#000000",
    bg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "MatchParen", {
    fg = "#9f8ce9",
    bold = true
  })


  -- ── Popup Menu ────────────────────────────────────────
  vim.api.nvim_set_hl(0, "Pmenu", {
    fg = "#8a96a7",
    bg = "#0c0c0e"
  })

  vim.api.nvim_set_hl(0, "PmenuSel", {
    fg = "#000000",
    bg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "PmenuSbar", {
    bg = "#141418"
  })

  vim.api.nvim_set_hl(0, "PmenuThumb", {
    bg = "#8a96a7"
  })


  -- ── Statusline & Winbar ───────────────────────────────
  vim.api.nvim_set_hl(0, "StatusLine", {
    fg = "#bcc7d5",
    bg = "#0c0c0e"
  })

  vim.api.nvim_set_hl(0, "StatusLineNC", {
    fg = "#8a96a7",
    bg = "#050507"
  })

  vim.api.nvim_set_hl(0, "StatusLineTerm", {
    fg = "#bcc7d5",
    bg = "#0c0c0e"
  })

  vim.api.nvim_set_hl(0, "StatusLineTermNC", {
    fg = "#8a96a7",
    bg = "#050507"
  })

  vim.api.nvim_set_hl(0, "WinBar", {
    fg = "#bcc7d5",
    bg = "#0c0c0e"
  })

  vim.api.nvim_set_hl(0, "WinBarNC", {
    fg = "#8a96a7",
    bg = "#050507"
  })

  vim.api.nvim_set_hl(0, "WinSeparator", {
    fg = "#6d7788"
  })


  -- ── Tabline ────────────────────────────────────────────
  vim.api.nvim_set_hl(0, "TabLine", {
    fg = "#8a96a7",
    bg = "#050507"
  })

  vim.api.nvim_set_hl(0, "TabLineSel", {
    fg = "#bcc7d5",
    bg = "#0c0c0e"
  })

  vim.api.nvim_set_hl(0, "TabLineFill", {
    bg = "#000000"
  })


  -- ── Folds ─────────────────────────────────────────────
  vim.api.nvim_set_hl(0, "Folded", {
    fg = "#8a96a7",
    bg = "#050507"
  })

  vim.api.nvim_set_hl(0, "FoldColumn", {
    fg = "#8a96a7"
  })


  -- ── Diff ──────────────────────────────────────────────
  vim.api.nvim_set_hl(0, "DiffAdd", {
    bg = "#183a2f"
  })

  vim.api.nvim_set_hl(0, "DiffChange", {
    bg = "#423410"
  })

  vim.api.nvim_set_hl(0, "DiffDelete", {
    bg = "#492b2c"
  })

  vim.api.nvim_set_hl(0, "DiffText", {
    bg = "#182d4f"
  })


  -- ── Spell ─────────────────────────────────────────────
  vim.api.nvim_set_hl(0, "SpellBad", {
    sp = "#e88484",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "SpellCap", {
    sp = "#d1a126",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "SpellLocal", {
    sp = "#62b9e2",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "SpellRare", {
    sp = "#b98beb",
    undercurl = true
  })


  -- ── Messages ──────────────────────────────────────────
  vim.api.nvim_set_hl(0, "MsgArea", {
    fg = "#bcc7d5"
  })

  vim.api.nvim_set_hl(0, "ModeMsg", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "WarningMsg", {
    fg = "#d1a126"
  })

  vim.api.nvim_set_hl(0, "ErrorMsg", {
    fg = "#e88484"
  })

  vim.api.nvim_set_hl(0, "Question", {
    fg = "#62b9e2"
  })


  -- ── Misc ──────────────────────────────────────────────
  vim.api.nvim_set_hl(0, "Title", {
    fg = "#a4afee",
    bold = true
  })

  vim.api.nvim_set_hl(0, "Directory", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "Conceal", {
    fg = "#8a96a7"
  })

  vim.api.nvim_set_hl(0, "TermCursor", {
    fg = "#000000",
    bg = "#a4afee"
  })


  -- ── Classic Syntax ────────────────────────────────────
  vim.api.nvim_set_hl(0, "Comment", {
    fg = "#a69ba6",
    italic = true
  })

  vim.api.nvim_set_hl(0, "Constant", {
    fg = "#b98beb"
  })

  vim.api.nvim_set_hl(0, "String", {
    fg = "#43b48b"
  })

  vim.api.nvim_set_hl(0, "Character", {
    fg = "#43b48b"
  })

  vim.api.nvim_set_hl(0, "Number", {
    fg = "#b98beb"
  })

  vim.api.nvim_set_hl(0, "Boolean", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "Float", {
    fg = "#b98beb"
  })

  vim.api.nvim_set_hl(0, "Identifier", {
    fg = "#8a96a7"
  })

  vim.api.nvim_set_hl(0, "Function", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "Statement", {
    fg = "#a4afee",
    bold = true
  })

  vim.api.nvim_set_hl(0, "Conditional", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "Repeat", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "Label", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "Operator", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "Keyword", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "Exception", {
    fg = "#e88484"
  })

  vim.api.nvim_set_hl(0, "PreProc", {
    fg = "#8c94a4"
  })

  vim.api.nvim_set_hl(0, "Include", {
    fg = "#8c94a4"
  })

  vim.api.nvim_set_hl(0, "Define", {
    fg = "#8c94a4"
  })

  vim.api.nvim_set_hl(0, "PreCondit", {
    fg = "#8c94a4"
  })

  vim.api.nvim_set_hl(0, "Type", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "StorageClass", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "Structure", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "Typedef", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "Special", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "SpecialChar", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "Delimiter", {
    fg = "#8a96a7"
  })

  vim.api.nvim_set_hl(0, "SpecialComment", {
    fg = "#a69ba6"
  })

  vim.api.nvim_set_hl(0, "Debug", {
    fg = "#d1a126"
  })

  vim.api.nvim_set_hl(0, "Underlined", {
    fg = "#62b9e2",
    underline = true
  })

  vim.api.nvim_set_hl(0, "Ignore", {
    fg = "#000000"
  })

  vim.api.nvim_set_hl(0, "Error", {
    fg = "#e88484"
  })

  vim.api.nvim_set_hl(0, "Todo", {
    fg = "#d1a126",
    bold = true
  })


  -- ── Treesitter ────────────────────────────────────────
  vim.api.nvim_set_hl(0, "@variable", {
    fg = "#8a96a7"
  })

  vim.api.nvim_set_hl(0, "@variable.builtin", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "@variable.parameter", {
    fg = "#b98beb"
  })

  vim.api.nvim_set_hl(0, "@variable.member", {
    fg = "#8a96a7"
  })

  vim.api.nvim_set_hl(0, "@constant", {
    fg = "#b98beb"
  })

  vim.api.nvim_set_hl(0, "@constant.builtin", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "@constant.macro", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "@module", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "@module.builtin", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "@label", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "@string", {
    fg = "#43b48b"
  })

  vim.api.nvim_set_hl(0, "@string.documentation", {
    fg = "#43b48b",
    italic = true
  })

  vim.api.nvim_set_hl(0, "@string.regex", {
    fg = "#d1a126"
  })

  vim.api.nvim_set_hl(0, "@string.escape", {
    fg = "#d1a126"
  })

  vim.api.nvim_set_hl(0, "@character", {
    fg = "#43b48b"
  })

  vim.api.nvim_set_hl(0, "@character.special", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "@number", {
    fg = "#b98beb"
  })

  vim.api.nvim_set_hl(0, "@boolean", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "@float", {
    fg = "#b98beb"
  })

  vim.api.nvim_set_hl(0, "@function", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "@function.builtin", {
    fg = "#9f8ce9",
    bold = true
  })

  vim.api.nvim_set_hl(0, "@function.call", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "@function.macro", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "@function.method", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "@function.method.call", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "@parameter", {
    fg = "#b98beb"
  })

  vim.api.nvim_set_hl(0, "@method", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "@field", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "@property", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "@constructor", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "@conditional", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "@repeat", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "@debug", {
    fg = "#d1a126"
  })

  vim.api.nvim_set_hl(0, "@include", {
    fg = "#8c94a4"
  })

  vim.api.nvim_set_hl(0, "@operator", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "@keyword", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "@keyword.function", {
    fg = "#a4afee",
    italic = true
  })

  vim.api.nvim_set_hl(0, "@keyword.operator", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "@keyword.return", {
    fg = "#a4afee",
    bold = true
  })

  vim.api.nvim_set_hl(0, "@exception", {
    fg = "#e88484"
  })

  vim.api.nvim_set_hl(0, "@type", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "@type.builtin", {
    fg = "#62b9e2",
    bold = true
  })

  vim.api.nvim_set_hl(0, "@type.definition", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "@type.qualifier", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "@storageclass", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "@attribute", {
    fg = "#8c94a4"
  })

  vim.api.nvim_set_hl(0, "@symbol", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "@punctuation.delimiter", {
    fg = "#8a96a7"
  })

  vim.api.nvim_set_hl(0, "@punctuation.bracket", {
    fg = "#8a96a7"
  })

  vim.api.nvim_set_hl(0, "@punctuation.special", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "@comment", {
    fg = "#a69ba6",
    italic = true
  })

  vim.api.nvim_set_hl(0, "@comment.error", {
    fg = "#e88484"
  })

  vim.api.nvim_set_hl(0, "@comment.warning", {
    fg = "#d1a126"
  })

  vim.api.nvim_set_hl(0, "@comment.todo", {
    fg = "#d1a126",
    bold = true
  })

  vim.api.nvim_set_hl(0, "@comment.note", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "@markup.strong", {
    bold = true
  })

  vim.api.nvim_set_hl(0, "@markup.italic", {
    italic = true
  })

  vim.api.nvim_set_hl(0, "@markup.strikethrough", {
    strikethrough = true
  })

  vim.api.nvim_set_hl(0, "@markup.underline", {
    underline = true
  })

  vim.api.nvim_set_hl(0, "@markup.heading", {
    fg = "#a4afee",
    bold = true
  })

  vim.api.nvim_set_hl(0, "@markup.quote", {
    fg = "#a69ba6",
    italic = true
  })

  vim.api.nvim_set_hl(0, "@markup.math", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "@markup.link", {
    fg = "#a4afee",
    underline = true
  })

  vim.api.nvim_set_hl(0, "@markup.link.label", {
    fg = "#a4afee",
    underline = true
  })

  vim.api.nvim_set_hl(0, "@markup.link.url", {
    fg = "#9f8ce9",
    underline = true
  })

  vim.api.nvim_set_hl(0, "@markup.raw", {
    fg = "#43b48b"
  })

  vim.api.nvim_set_hl(0, "@markup.list", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "@diff.plus", {
    fg = "#43b48b"
  })

  vim.api.nvim_set_hl(0, "@diff.minus", {
    fg = "#e88484"
  })

  vim.api.nvim_set_hl(0, "@diff.delta", {
    fg = "#d1a126"
  })

  vim.api.nvim_set_hl(0, "@tag", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "@tag.attribute", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "@tag.delimiter", {
    fg = "#8a96a7"
  })


  -- ── LSP / Diagnostics ────────────────────────────────
  vim.api.nvim_set_hl(0, "DiagnosticError", {
    fg = "#e88484"
  })

  vim.api.nvim_set_hl(0, "DiagnosticWarn", {
    fg = "#d1a126"
  })

  vim.api.nvim_set_hl(0, "DiagnosticInfo", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "DiagnosticHint", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "DiagnosticOk", {
    fg = "#43b48b"
  })

  vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", {
    sp = "#e88484",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", {
    sp = "#d1a126",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", {
    sp = "#62b9e2",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", {
    sp = "#9f8ce9",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", {
    fg = "#e88484"
  })

  vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", {
    fg = "#d1a126"
  })

  vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "DiagnosticFloatingError", {
    fg = "#e88484"
  })

  vim.api.nvim_set_hl(0, "DiagnosticFloatingWarn", {
    fg = "#d1a126"
  })

  vim.api.nvim_set_hl(0, "DiagnosticFloatingInfo", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "DiagnosticFloatingHint", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "DiagnosticSignError", {
    fg = "#e88484"
  })

  vim.api.nvim_set_hl(0, "DiagnosticSignWarn", {
    fg = "#d1a126"
  })

  vim.api.nvim_set_hl(0, "DiagnosticSignInfo", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "DiagnosticSignHint", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "LspReferenceText", {
    bg = "#0c0c0e"
  })

  vim.api.nvim_set_hl(0, "LspReferenceRead", {
    bg = "#0c0c0e"
  })

  vim.api.nvim_set_hl(0, "LspReferenceWrite", {
    bg = "#0c0c0e"
  })

  vim.api.nvim_set_hl(0, "LspInlayHint", {
    fg = "#a69ba6",
    bg = "#050507"
  })


  -- ── Telescope ─────────────────────────────────────────
  vim.api.nvim_set_hl(0, "TelescopeNormal", {
    fg = "#bcc7d5",
    bg = "#000000"
  })

  vim.api.nvim_set_hl(0, "TelescopeBorder", {
    fg = "#6d7788",
    bg = "#000000"
  })

  vim.api.nvim_set_hl(0, "TelescopeTitle", {
    fg = "#a4afee",
    bold = true
  })

  vim.api.nvim_set_hl(0, "TelescopePromptNormal", {
    fg = "#bcc7d5",
    bg = "#050507"
  })

  vim.api.nvim_set_hl(0, "TelescopePromptBorder", {
    fg = "#6d7788",
    bg = "#050507"
  })

  vim.api.nvim_set_hl(0, "TelescopePromptTitle", {
    fg = "#9f8ce9",
    bold = true
  })

  vim.api.nvim_set_hl(0, "TelescopeSelection", {
    fg = "#bcc7d5",
    bg = "#141418"
  })

  vim.api.nvim_set_hl(0, "TelescopeMultiSelection", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "TelescopeMatching", {
    fg = "#a4afee",
    bold = true
  })

  vim.api.nvim_set_hl(0, "TelescopePreviewNormal", {
    fg = "#bcc7d5",
    bg = "#050507"
  })

  vim.api.nvim_set_hl(0, "TelescopePreviewBorder", {
    fg = "#6d7788",
    bg = "#050507"
  })

  vim.api.nvim_set_hl(0, "TelescopeResultsNormal", {
    fg = "#bcc7d5",
    bg = "#000000"
  })

  vim.api.nvim_set_hl(0, "TelescopeResultsBorder", {
    fg = "#6d7788",
    bg = "#000000"
  })


  -- ── NvimTree ─────────────────────────────────────────
  vim.api.nvim_set_hl(0, "NvimTreeNormal", {
    fg = "#bcc7d5",
    bg = "#000000"
  })

  vim.api.nvim_set_hl(0, "NvimTreeRootFolder", {
    fg = "#a4afee",
    bold = true
  })

  vim.api.nvim_set_hl(0, "NvimTreeGitDirty", {
    fg = "#d1a126"
  })

  vim.api.nvim_set_hl(0, "NvimTreeGitNew", {
    fg = "#43b48b"
  })

  vim.api.nvim_set_hl(0, "NvimTreeGitDeleted", {
    fg = "#e88484"
  })

  vim.api.nvim_set_hl(0, "NvimTreeOpenedFile", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "NvimTreeSpecialFile", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "NvimTreeSymlink", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "NvimTreeFolderName", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "NvimTreeFolderIcon", {
    fg = "#8a96a7"
  })

  vim.api.nvim_set_hl(0, "NvimTreeEmptyFolderName", {
    fg = "#8a96a7"
  })

  vim.api.nvim_set_hl(0, "NvimTreeOpenedFolderName", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "NvimTreeImageFile", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", {
    fg = "#6d7788"
  })

  vim.api.nvim_set_hl(0, "NvimTreeWinSeparator", {
    fg = "#6d7788",
    bg = "#000000"
  })

  vim.api.nvim_set_hl(0, "NvimTreeCursorLine", {
    bg = "#050507"
  })


  -- ── WhichKey ─────────────────────────────────────────
  vim.api.nvim_set_hl(0, "WhichKey", {
    fg = "#a4afee",
    bold = true
  })

  vim.api.nvim_set_hl(0, "WhichKeyGroup", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "WhichKeyDesc", {
    fg = "#bcc7d5"
  })

  vim.api.nvim_set_hl(0, "WhichKeySeperator", {
    fg = "#8a96a7"
  })

  vim.api.nvim_set_hl(0, "WhichKeySeparator", {
    fg = "#8a96a7"
  })

  vim.api.nvim_set_hl(0, "WhichKeyFloat", {
    fg = "#bcc7d5",
    bg = "#050507"
  })

  vim.api.nvim_set_hl(0, "WhichKeyBorder", {
    fg = "#6d7788"
  })

  vim.api.nvim_set_hl(0, "WhichKeyValue", {
    fg = "#b98beb"
  })


  -- ── Lazy / Noice / Cmp ───────────────────────────────
  vim.api.nvim_set_hl(0, "LazyNormal", {
    fg = "#bcc7d5",
    bg = "#000000"
  })

  vim.api.nvim_set_hl(0, "LazyReasonPlugin", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "LazyReasonStart", {
    fg = "#43b48b"
  })

  vim.api.nvim_set_hl(0, "LazyReasonSource", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "LazyReasonRt", {
    fg = "#b98beb"
  })

  vim.api.nvim_set_hl(0, "LazyReasonCmd", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "LazyValue", {
    fg = "#b98beb"
  })

  vim.api.nvim_set_hl(0, "LazyCommit", {
    fg = "#43b48b"
  })

  vim.api.nvim_set_hl(0, "LazySpecial", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "LazyDir", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "LazyH1", {
    fg = "#a4afee",
    bold = true
  })

  vim.api.nvim_set_hl(0, "LazyButton", {
    fg = "#bcc7d5",
    bg = "#0c0c0e"
  })

  vim.api.nvim_set_hl(0, "LazyButtonActive", {
    fg = "#000000",
    bg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "NoiceMsg", {
    fg = "#bcc7d5"
  })

  vim.api.nvim_set_hl(0, "NoiceCursor", {
    fg = "#000000",
    bg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "MiniCompletionActiveParameter", {
    underline = true
  })

  vim.api.nvim_set_hl(0, "CmpItemAbbr", {
    fg = "#bcc7d5"
  })

  vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", {
    fg = "#a4afee",
    bold = true
  })

  vim.api.nvim_set_hl(0, "CmpItemAbbrMatchFuzzy", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "CmpItemKind", {
    fg = "#8a96a7"
  })

  vim.api.nvim_set_hl(0, "CmpItemMenu", {
    fg = "#8a96a7"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindSnippet", {
    fg = "#b98beb"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindKeyword", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindText", {
    fg = "#bcc7d5"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindMethod", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindFunction", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindConstructor", {
    fg = "#a4afee"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindField", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindVariable", {
    fg = "#b98beb"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindClass", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindInterface", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindModule", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindProperty", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindUnit", {
    fg = "#43b48b"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindValue", {
    fg = "#b98beb"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindEnum", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindEnumMember", {
    fg = "#b98beb"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindColor", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindFile", {
    fg = "#bcc7d5"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindReference", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindFolder", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindEvent", {
    fg = "#d1a126"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindOperator", {
    fg = "#9f8ce9"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindTypeParameter", {
    fg = "#62b9e2"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindCopied", {
    fg = "#43b48b"
  })


  -- ── GitSigns ────────────────────────────────────────
  vim.api.nvim_set_hl(0, "GitSignsAdd", {
    fg = "#43b48b"
  })

  vim.api.nvim_set_hl(0, "GitSignsChange", {
    fg = "#d1a126"
  })

  vim.api.nvim_set_hl(0, "GitSignsDelete", {
    fg = "#e88484"
  })

  vim.api.nvim_set_hl(0, "GitSignsAddNr", {
    fg = "#43b48b"
  })

  vim.api.nvim_set_hl(0, "GitSignsChangeNr", {
    fg = "#d1a126"
  })

  vim.api.nvim_set_hl(0, "GitSignsDeleteNr", {
    fg = "#e88484"
  })

  vim.api.nvim_set_hl(0, "GitSignsAddLn", {
    bg = "#050e0b"
  })

  vim.api.nvim_set_hl(0, "GitSignsChangeLn", {
    bg = "#110d03"
  })

  vim.api.nvim_set_hl(0, "GitSignsDeleteLn", {
    bg = "#130b0b"
  })

  vim.api.nvim_set_hl(0, "GitSignsCurrentLineBlame", {
    fg = "#8a96a7"
  })
