# =====================================================
# 🌟 STARSHIP CONFIGURATION FOR ROOT
# =====================================================
# Custom Starship configuration for root user
# Similar to user prompt but with fire icon

"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os$username$directory$git_branch$git_status$git_metrics$nodejs$bun$rust$python$golang$java$package$jobs$cmd_duration$status
$character"""

add_newline = false
command_timeout = 500

[character]
success_symbol = "[❯](bold #50C7E3)"
error_symbol = "[❯](bold #FF6B6B)"
vicmd_symbol = "[❮](bold #FFD93D)"

[os]
format = "[$symbol ]($style)"
style = "bold #6A9BD1"
disabled = false

[os.symbols]
Arch = "󰣇"
Ubuntu = "󰕈"
Debian = "󰣚"
Fedora = "󰣛"
Macos = "󰀵"
Windows = "󰍲"

[username]
style_user = "bold #A8DADC"
style_root = "bold #FF6B6B"
format = "[🔥]($style) "
disabled = false
show_always = true

[directory]
truncation_length = 3
truncation_symbol = "…/"
read_only = " "
style = "bold #50C7E3"
format = "[$path]($style)[$read_only](bold #FF6B6B)"
home_symbol = "~"
fish_style_pwd_dir_length = 1
use_logical_path = true

[git_branch]
symbol = " "
style = "bold #FFD93D"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold #FF6B6B"
format = "([\\[$all_status$ahead_behind\\]]($style) )"
disabled = false

[git_metrics]
disabled = false
added_style = "bold blue"
deleted_style = "bold red"
format = "([+$added]($added_style) )([-$deleted]($deleted_style) )"

[nodejs]
symbol = " "
style = "bold #68A063"
format = "[$symbol($version )]($style)"

[bun]
symbol = " "
style = "bold #FBF0DF"
format = "[$symbol($version )]($style)"

[rust]
symbol = " "
style = "bold #DEA584"
format = "[$symbol($version )]($style)"

[python]
symbol = " "
style = "bold #306998"
format = "[$symbol($version )]($style)"

[golang]
symbol = " "
style = "bold #5194C4"
format = "[$symbol($version )]($style)"

[java]
symbol = " "
style = "bold #ED8B00"
format = "[$symbol($version )]($style)"

[package]
symbol = " "
style = "bold #F7931E"
format = "[$symbol$version]($style) "

[jobs]
symbol = "+"
style = "bold #19CC9C"
format = "[$symbol$number]($style) "

[cmd_duration]
min_time = 2000
style = "bold #F7931E"
format = "took [$duration]($style) "

[status]
style = "bold #FF6B6B"
symbol = "✘"
success_symbol = "✓"
not_executable_symbol = "🚫"
not_found_symbol = "🔍"
sigint_symbol = "🧱"
signal_symbol = "⚡"
format = "[$symbol $common_meaning$signal_name$maybe_int]($style) "
map_symbol = true
disabled = false

[line_break]
disabled = false

[hostname]
ssh_only = true
format = "[$hostname](bold blue) "
trim_at = "."
disabled = false