"""Neovim highlight group chunks for Dreamcoder."""

from __future__ import annotations

from typing import Callable

from .palette import mix


Hl = Callable[..., str]


def nvim_lsp_groups(hl: Hl, c: dict[str, str], fg: str, bg: str, sel_fg: str, sel_bg: str) -> list[str]:
    return [
        hl("@markup.strong", bold=True),
        hl("@markup.italic", italic=True),
        hl("@markup.strikethrough", strikethrough=True),
        hl("@markup.underline", underline=True),
        hl("@markup.heading", fg=c["accent"], bold=True),
        hl("@markup.quote", fg=c["comment"], italic=True),
        hl("@markup.math", fg=c["lavender"]),
        hl("@markup.link", fg=c["diagnostic"], underline=True),
        hl("@markup.link.label", fg=c["diagnostic"], underline=True),
        hl("@markup.link.url", fg=c["subtle"], underline=True),
        hl("@markup.raw", fg=c["sage"]),
        hl("@markup.list", fg=c["accent"]),
        hl("@diff.plus", fg=c["sage"]),
        hl("@diff.minus", fg=c["error"]),
        hl("@diff.delta", fg=c["warning"]),
        hl("@tag", fg=c["accent"]),
        hl("@tag.attribute", fg=c["diagnostic"]),
        hl("@tag.delimiter", fg=c["muted"]),
        "",
        "  -- ── LSP / Diagnostics ────────────────────────────────",
        hl("DiagnosticError", fg=c["error"]),
        hl("DiagnosticWarn", fg=c["warning"]),
        hl("DiagnosticInfo", fg=c["diagnostic"]),
        hl("DiagnosticHint", fg=c["lavender"]),
        hl("DiagnosticOk", fg=c["sage"]),
        hl("DiagnosticUnderlineError", sp=c["error"], undercurl=True),
        hl("DiagnosticUnderlineWarn", sp=c["warning"], undercurl=True),
        hl("DiagnosticUnderlineInfo", sp=c["diagnostic"], undercurl=True),
        hl("DiagnosticUnderlineHint", sp=c["lavender"], undercurl=True),
        hl("DiagnosticVirtualTextError", fg=c["error"]),
        hl("DiagnosticVirtualTextWarn", fg=c["warning"]),
        hl("DiagnosticVirtualTextInfo", fg=c["diagnostic"]),
        hl("DiagnosticVirtualTextHint", fg=c["lavender"]),
        hl("DiagnosticFloatingError", fg=c["error"]),
        hl("DiagnosticFloatingWarn", fg=c["warning"]),
        hl("DiagnosticFloatingInfo", fg=c["diagnostic"]),
        hl("DiagnosticFloatingHint", fg=c["lavender"]),
        hl("DiagnosticSignError", fg=c["error"]),
        hl("DiagnosticSignWarn", fg=c["warning"]),
        hl("DiagnosticSignInfo", fg=c["diagnostic"]),
        hl("DiagnosticSignHint", fg=c["lavender"]),
        hl("LspReferenceText", bg=c["surface1"]),
        hl("LspReferenceRead", bg=c["surface1"]),
        hl("LspReferenceWrite", bg=c["surface1"]),
        hl("LspInlayHint", fg=c["comment"], bg=c["surface0"]),
        "",
        "  -- ── Telescope ─────────────────────────────────────────",
        hl("TelescopeNormal", fg=fg, bg=bg),
        hl("TelescopeBorder", fg=c["border_ui"], bg=bg),
        hl("TelescopeTitle", fg=c["accent"], bold=True),
        hl("TelescopePromptNormal", fg=fg, bg=c["surface0"]),
        hl("TelescopePromptBorder", fg=c["border_ui"], bg=c["surface0"]),
        hl("TelescopePromptTitle", fg=c["accent_2"], bold=True),
        hl("TelescopeSelection", fg=sel_fg, bg=sel_bg),
        hl("TelescopeMultiSelection", fg=c["accent"]),
        hl("TelescopeMatching", fg=c["accent"], bold=True),
        hl("TelescopePreviewNormal", fg=fg, bg=c["surface0"]),
        hl("TelescopePreviewBorder", fg=c["border_ui"], bg=c["surface0"]),
        hl("TelescopeResultsNormal", fg=fg, bg=bg),
        hl("TelescopeResultsBorder", fg=c["border_ui"], bg=bg),
        "",
        "  -- ── NvimTree ─────────────────────────────────────────",
        hl("NvimTreeNormal", fg=fg, bg=bg),
        hl("NvimTreeRootFolder", fg=c["accent"], bold=True),
        hl("NvimTreeGitDirty", fg=c["warning"]),
        hl("NvimTreeGitNew", fg=c["sage"]),
        hl("NvimTreeGitDeleted", fg=c["error"]),
        hl("NvimTreeOpenedFile", fg=c["accent_2"]),
        hl("NvimTreeSpecialFile", fg=c["accent"]),
        hl("NvimTreeSymlink", fg=c["diagnostic"]),
        hl("NvimTreeFolderName", fg=c["diagnostic"]),
        hl("NvimTreeFolderIcon", fg=c["muted"]),
        hl("NvimTreeEmptyFolderName", fg=c["muted"]),
        hl("NvimTreeOpenedFolderName", fg=c["accent"]),
        hl("NvimTreeImageFile", fg=c["lavender"]),
        hl("NvimTreeIndentMarker", fg=c["border_ui"]),
        hl("NvimTreeWinSeparator", fg=c["border_ui"], bg=bg),
        hl("NvimTreeCursorLine", bg=c["surface0"]),
        "",
        "  -- ── WhichKey ─────────────────────────────────────────",
    ]
