"""Extra theme renderers for Dreamcoder ecosystem expansion.

Each renderer takes a palette dict from palette.adaptive_palette()
and returns a string suitable for write_if_changed().

Targets: Neovim, Zsh-syntax-highlighting, LS_COLORS/eza, Bat, Delta,
         Fzf, Btop, Dunst, Firefox userChrome, Obsidian, Cava.
"""

from __future__ import annotations

from .palette import guard, mix
from .renderers_core import ansi


# ── Neovim Lua Colorscheme ────────────────────────────────────────


def nvim_content(c: dict[str, str]) -> str:
    """Return a Neovim Lua colorscheme using the Dreamcoder palette."""
    def hl(name, **kwargs):
        parts = []
        if "fg" in kwargs:
            parts.append(f'    fg = "{kwargs["fg"]}"')
        if "bg" in kwargs:
            parts.append(f'    bg = "{kwargs["bg"]}"')
        if "sp" in kwargs:
            parts.append(f'    sp = "{kwargs["sp"]}"')
        if "bold" in kwargs and kwargs["bold"]:
            parts.append("    bold = true")
        if "italic" in kwargs and kwargs["italic"]:
            parts.append("    italic = true")
        if "underline" in kwargs and kwargs["underline"]:
            parts.append("    underline = true")
        if "undercurl" in kwargs and kwargs["undercurl"]:
            parts.append("    undercurl = true")
        if "strikethrough" in kwargs and kwargs["strikethrough"]:
            parts.append("    strikethrough = true")
        if "reverse" in kwargs and kwargs["reverse"]:
            parts.append("    reverse = true")
        inner = ",\n".join(parts)
        return f'  vim.api.nvim_set_hl(0, "{name}", {{\n{inner}\n  }})\n'

    invert = c.get("details") == "lighter"
    bg = c["bg"]
    text = c["text"]
    fg = text
    # Selection: invert in light/dusk (bg ↔ text), use selection color in dark
    sel_bg = c["text"] if invert else c["selection"]
    sel_fg = c["bg"] if invert else c["text"]

    lines = [
        f"""-- ========================================================
-- {c['name']} — generated by Dreamcoder sync
-- ========================================================
-- Usage: vim.cmd.colorscheme("dreamcoder")
-- ========================================================

vim.g.colors_name = "dreamcoder"

-- Glass blur: transparent background + subtle float transparency
vim.opt.winblend = 10
vim.opt.pumblend = 10

local c = {{
  bg        = "{bg}",
  surface0  = "{c['surface0']}",
  surface1  = "{c['surface1']}",
  surface2  = "{c['surface2']}",
  text      = "{text}",
  muted     = "{c['muted']}",
  subtle    = "{c['subtle']}",
  comment   = "{c['comment']}",
  accent    = "{c['accent']}",
  accent2   = "{c['accent_2']}",
  diagnostic = "{c['diagnostic']}",
  sage      = "{c['sage']}",
  lavender  = "{c['lavender']}",
  mauve     = "{c['mauve']}",
  error     = "{c['error']}",
  warning   = "{c['warning']}",
  border    = "{c['border']}",
  border_ui = "{c['border_ui']}",
  selection = "{sel_bg}",
}}

local function h(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end

-- ── Editor UI ────────────────────────────────────────────────
-- Normal background = "none" for glass blur effect.
-- Terminal (Kitty/Ghostty) handles transparency + blur.
""",
        hl("Normal", fg=fg, bg="none"),
        hl("NormalFloat", fg=fg, bg=c["surface0"]),
        hl("FloatBorder", fg=c["border_ui"], bg=c["surface0"]),
        hl("NonText", fg=c["subtle"]),
        hl("SpecialKey", fg=c["muted"]),
        hl("Whitespace", fg=c["border"]),
        hl("EndOfBuffer", fg="none"),
        hl("Cursor", fg=bg, bg=c["accent"]),
        hl("lCursor", fg=bg, bg=c["accent"]),
        hl("CursorLine", bg=c["surface0"]),
        hl("CursorLineNr", fg=c["accent"], bold=True),
        hl("LineNr", fg=c["muted"]),
        hl("CursorColumn", bg=c["surface0"]),
        hl("ColorColumn", bg=c["surface0"]),
        hl("SignColumn", bg="none"),
        "",
        "  -- ── Selection & Search ───────────────────────────────",
        hl("Visual", fg=sel_fg, bg=sel_bg),
        hl("VisualNOS", fg=sel_fg, bg=sel_bg),
        hl("Search", fg=bg, bg=c["accent"]),
        hl("IncSearch", fg=bg, bg=c["accent_2"]),
        hl("CurSearch", fg=bg, bg=c["accent"]),
        hl("Substitute", fg=bg, bg=c["accent_2"]),
        hl("MatchParen", fg=c["accent_2"], bold=True),
        "",
        "  -- ── Popup Menu ────────────────────────────────────────",
        hl("Pmenu", fg=c["muted"], bg=c["surface1"]),
        hl("PmenuSel", fg=bg, bg=c["accent"]),
        hl("PmenuSbar", bg=c["surface2"]),
        hl("PmenuThumb", bg=c["muted"]),
        "",
        "  -- ── Statusline & Winbar ───────────────────────────────",
        hl("StatusLine", fg=fg, bg=c["surface1"]),
        hl("StatusLineNC", fg=c["muted"], bg=c["surface0"]),
        hl("StatusLineTerm", fg=fg, bg=c["surface1"]),
        hl("StatusLineTermNC", fg=c["muted"], bg=c["surface0"]),
        hl("WinBar", fg=fg, bg=c["surface1"]),
        hl("WinBarNC", fg=c["muted"], bg=c["surface0"]),
        hl("WinSeparator", fg=c["border"]),
        "",
        "  -- ── Tabline ────────────────────────────────────────────",
        hl("TabLine", fg=c["muted"], bg=c["surface0"]),
        hl("TabLineSel", fg=fg, bg=c["surface1"]),
        hl("TabLineFill", bg=bg),
        "",
        "  -- ── Folds ─────────────────────────────────────────────",
        hl("Folded", fg=c["muted"], bg=c["surface0"]),
        hl("FoldColumn", fg=c["muted"]),
        "",
        "  -- ── Diff ──────────────────────────────────────────────",
        hl("DiffAdd", bg=mix(c["sage"], c["surface0"], 0.7)),
        hl("DiffChange", bg=mix(c["warning"], c["surface0"], 0.7)),
        hl("DiffDelete", bg=mix(c["error"], c["surface0"], 0.7)),
        hl("DiffText", bg=mix(c.get("focus", c["accent"]), c["surface0"], 0.65)),
        "",
        "  -- ── Spell ─────────────────────────────────────────────",
        hl("SpellBad", sp=c["error"], undercurl=True),
        hl("SpellCap", sp=c["warning"], undercurl=True),
        hl("SpellLocal", sp=c["diagnostic"], undercurl=True),
        hl("SpellRare", sp=c["mauve"], undercurl=True),
        "",
        "  -- ── Messages ──────────────────────────────────────────",
        hl("MsgArea", fg=fg),
        hl("ModeMsg", fg=c["accent"]),
        hl("WarningMsg", fg=c["warning"]),
        hl("ErrorMsg", fg=c["error"]),
        hl("Question", fg=c["diagnostic"]),
        "",
        "  -- ── Misc ──────────────────────────────────────────────",
        hl("Title", fg=c["accent"], bold=True),
        hl("Directory", fg=c["diagnostic"]),
        hl("Conceal", fg=c["muted"]),
        hl("TermCursor", fg=bg, bg=c["accent"]),
        "",
        "  -- ── Classic Syntax ────────────────────────────────────",
        hl("Comment", fg=c["comment"], italic=True),
        hl("Constant", fg=c["mauve"]),
        hl("String", fg=c["sage"]),
        hl("Character", fg=c["sage"]),
        hl("Number", fg=c["mauve"]),
        hl("Boolean", fg=c["lavender"]),
        hl("Float", fg=c["mauve"]),
        hl("Identifier", fg=fg),
        hl("Function", fg=c["accent_2"]),
        hl("Statement", fg=c["accent"], bold=True),
        hl("Conditional", fg=c["accent"]),
        hl("Repeat", fg=c["accent"]),
        hl("Label", fg=c["accent"]),
        hl("Operator", fg=c["accent_2"]),
        hl("Keyword", fg=c["accent"]),
        hl("Exception", fg=c["error"]),
        hl("PreProc", fg=c["subtle"]),
        hl("Include", fg=c["subtle"]),
        hl("Define", fg=c["subtle"]),
        hl("PreCondit", fg=c["subtle"]),
        hl("Type", fg=c["diagnostic"]),
        hl("StorageClass", fg=c["accent"]),
        hl("Structure", fg=c["diagnostic"]),
        hl("Typedef", fg=c["diagnostic"]),
        hl("Special", fg=c["lavender"]),
        hl("SpecialChar", fg=c["lavender"]),
        hl("Delimiter", fg=c["muted"]),
        hl("SpecialComment", fg=c["comment"]),
        hl("Debug", fg=c["warning"]),
        hl("Underlined", fg=c["diagnostic"], underline=True),
        hl("Ignore", fg=bg),
        hl("Error", fg=c["error"]),
        hl("Todo", fg=c["warning"], bold=True),
        "",
        "  -- ── Treesitter ────────────────────────────────────────",
        hl("@variable", fg=fg),
        hl("@variable.builtin", fg=c["lavender"]),
        hl("@variable.parameter", fg=c["mauve"]),
        hl("@variable.member", fg=fg),
        hl("@constant", fg=c["mauve"]),
        hl("@constant.builtin", fg=c["lavender"]),
        hl("@constant.macro", fg=c["accent"]),
        hl("@module", fg=c["diagnostic"]),
        hl("@module.builtin", fg=c["accent"]),
        hl("@label", fg=c["accent_2"]),
        hl("@string", fg=c["sage"]),
        hl("@string.documentation", fg=c["sage"], italic=True),
        hl("@string.regex", fg=c["accent_2"]),
        hl("@string.escape", fg=c["accent_2"]),
        hl("@character", fg=c["sage"]),
        hl("@character.special", fg=c["lavender"]),
        hl("@number", fg=c["mauve"]),
        hl("@boolean", fg=c["lavender"]),
        hl("@float", fg=c["mauve"]),
        hl("@function", fg=c["accent_2"]),
        hl("@function.builtin", fg=c["accent_2"], bold=True),
        hl("@function.call", fg=c["accent_2"]),
        hl("@function.macro", fg=c["accent_2"]),
        hl("@function.method", fg=c["accent_2"]),
        hl("@function.method.call", fg=c["accent_2"]),
        hl("@parameter", fg=c["mauve"]),
        hl("@method", fg=c["accent_2"]),
        hl("@field", fg=c["diagnostic"]),
        hl("@property", fg=c["diagnostic"]),
        hl("@constructor", fg=c["accent"]),
        hl("@conditional", fg=c["accent"]),
        hl("@repeat", fg=c["accent"]),
        hl("@debug", fg=c["warning"]),
        hl("@include", fg=c["subtle"]),
        hl("@operator", fg=c["accent_2"]),
        hl("@keyword", fg=c["accent"]),
        hl("@keyword.function", fg=c["accent"], italic=True),
        hl("@keyword.operator", fg=c["accent_2"]),
        hl("@keyword.return", fg=c["accent"], bold=True),
        hl("@exception", fg=c["error"]),
        hl("@type", fg=c["diagnostic"]),
        hl("@type.builtin", fg=c["diagnostic"], bold=True),
        hl("@type.definition", fg=c["diagnostic"]),
        hl("@type.qualifier", fg=c["accent"]),
        hl("@storageclass", fg=c["accent"]),
        hl("@attribute", fg=c["subtle"]),
        hl("@symbol", fg=c["lavender"]),
        hl("@punctuation.delimiter", fg=c["muted"]),
        hl("@punctuation.bracket", fg=c["muted"]),
        hl("@punctuation.special", fg=c["lavender"]),
        hl("@comment", fg=c["comment"], italic=True),
        hl("@comment.error", fg=c["error"]),
        hl("@comment.warning", fg=c["warning"]),
        hl("@comment.todo", fg=c["warning"], bold=True),
        hl("@comment.note", fg=c["diagnostic"]),
        hl("@markup.strong", bold=True),
        hl("@markup.italic", italic=True),
        hl("@markup.strikethrough", strikethrough=True),
        hl("@markup.underline", underline=True),
        hl("@markup.heading", fg=c["accent"], bold=True),
        hl("@markup.quote", fg=c["comment"], italic=True),
        hl("@markup.math", fg=c["lavender"]),
        hl("@markup.link", fg=c["diagnostic"], underline=True),
        hl("@markup.link.label", fg=c["diagnostic"], underline=True),
        hl("@markup.link.url", fg=c["subtle"], underline=True),
        hl("@markup.raw", fg=c["sage"]),
        hl("@markup.list", fg=c["accent"]),
        hl("@diff.plus", fg=c["sage"]),
        hl("@diff.minus", fg=c["error"]),
        hl("@diff.delta", fg=c["warning"]),
        hl("@tag", fg=c["accent"]),
        hl("@tag.attribute", fg=c["diagnostic"]),
        hl("@tag.delimiter", fg=c["muted"]),
        "",
        "  -- ── LSP / Diagnostics ────────────────────────────────",
        hl("DiagnosticError", fg=c["error"]),
        hl("DiagnosticWarn", fg=c["warning"]),
        hl("DiagnosticInfo", fg=c["diagnostic"]),
        hl("DiagnosticHint", fg=c["lavender"]),
        hl("DiagnosticOk", fg=c["sage"]),
        hl("DiagnosticUnderlineError", sp=c["error"], undercurl=True),
        hl("DiagnosticUnderlineWarn", sp=c["warning"], undercurl=True),
        hl("DiagnosticUnderlineInfo", sp=c["diagnostic"], undercurl=True),
        hl("DiagnosticUnderlineHint", sp=c["lavender"], undercurl=True),
        hl("DiagnosticVirtualTextError", fg=c["error"]),
        hl("DiagnosticVirtualTextWarn", fg=c["warning"]),
        hl("DiagnosticVirtualTextInfo", fg=c["diagnostic"]),
        hl("DiagnosticVirtualTextHint", fg=c["lavender"]),
        hl("DiagnosticFloatingError", fg=c["error"]),
        hl("DiagnosticFloatingWarn", fg=c["warning"]),
        hl("DiagnosticFloatingInfo", fg=c["diagnostic"]),
        hl("DiagnosticFloatingHint", fg=c["lavender"]),
        hl("DiagnosticSignError", fg=c["error"]),
        hl("DiagnosticSignWarn", fg=c["warning"]),
        hl("DiagnosticSignInfo", fg=c["diagnostic"]),
        hl("DiagnosticSignHint", fg=c["lavender"]),
        hl("LspReferenceText", bg=c["surface1"]),
        hl("LspReferenceRead", bg=c["surface1"]),
        hl("LspReferenceWrite", bg=c["surface1"]),
        hl("LspInlayHint", fg=c["comment"], bg=c["surface0"]),
        "",
        "  -- ── Telescope ─────────────────────────────────────────",
        hl("TelescopeNormal", fg=fg, bg=bg),
        hl("TelescopeBorder", fg=c["border_ui"], bg=bg),
        hl("TelescopeTitle", fg=c["accent"], bold=True),
        hl("TelescopePromptNormal", fg=fg, bg=c["surface0"]),
        hl("TelescopePromptBorder", fg=c["border_ui"], bg=c["surface0"]),
        hl("TelescopePromptTitle", fg=c["accent_2"], bold=True),
        hl("TelescopeSelection", fg=sel_fg, bg=sel_bg),
        hl("TelescopeMultiSelection", fg=c["accent"]),
        hl("TelescopeMatching", fg=c["accent"], bold=True),
        hl("TelescopePreviewNormal", fg=fg, bg=c["surface0"]),
        hl("TelescopePreviewBorder", fg=c["border_ui"], bg=c["surface0"]),
        hl("TelescopeResultsNormal", fg=fg, bg=bg),
        hl("TelescopeResultsBorder", fg=c["border_ui"], bg=bg),
        "",
        "  -- ── NvimTree ─────────────────────────────────────────",
        hl("NvimTreeNormal", fg=fg, bg=bg),
        hl("NvimTreeRootFolder", fg=c["accent"], bold=True),
        hl("NvimTreeGitDirty", fg=c["warning"]),
        hl("NvimTreeGitNew", fg=c["sage"]),
        hl("NvimTreeGitDeleted", fg=c["error"]),
        hl("NvimTreeOpenedFile", fg=c["accent_2"]),
        hl("NvimTreeSpecialFile", fg=c["accent"]),
        hl("NvimTreeSymlink", fg=c["diagnostic"]),
        hl("NvimTreeFolderName", fg=c["diagnostic"]),
        hl("NvimTreeFolderIcon", fg=c["muted"]),
        hl("NvimTreeEmptyFolderName", fg=c["muted"]),
        hl("NvimTreeOpenedFolderName", fg=c["accent"]),
        hl("NvimTreeImageFile", fg=c["lavender"]),
        hl("NvimTreeIndentMarker", fg=c["border"]),
        hl("NvimTreeWinSeparator", fg=c["border_ui"], bg=bg),
        hl("NvimTreeCursorLine", bg=c["surface0"]),
        "",
        "  -- ── WhichKey ─────────────────────────────────────────",
        hl("WhichKey", fg=c["accent"], bold=True),
        hl("WhichKeyGroup", fg=c["diagnostic"]),
        hl("WhichKeyDesc", fg=fg),
        hl("WhichKeySeperator", fg=c["muted"]),
        hl("WhichKeySeparator", fg=c["muted"]),
        hl("WhichKeyFloat", fg=fg, bg=c["surface0"]),
        hl("WhichKeyBorder", fg=c["border_ui"]),
        hl("WhichKeyValue", fg=c["mauve"]),
        "",
        "  -- ── Lazy / Noice / Cmp ───────────────────────────────",
        hl("LazyNormal", fg=fg, bg=bg),
        hl("LazyReasonPlugin", fg=c["accent"]),
        hl("LazyReasonStart", fg=c["sage"]),
        hl("LazyReasonSource", fg=c["diagnostic"]),
        hl("LazyReasonRt", fg=c["mauve"]),
        hl("LazyReasonCmd", fg=c["lavender"]),
        hl("LazyValue", fg=c["mauve"]),
        hl("LazyCommit", fg=c["sage"]),
        hl("LazySpecial", fg=c["lavender"]),
        hl("LazyDir", fg=c["diagnostic"]),
        hl("LazyH1", fg=c["accent"], bold=True),
        hl("LazyButton", fg=fg, bg=c["surface1"]),
        hl("LazyButtonActive", fg=bg, bg=c["accent"]),
        hl("NoiceMsg", fg=fg),
        hl("NoiceCursor", fg=bg, bg=c["accent"]),
        hl("MiniCompletionActiveParameter", underline=True),
        hl("CmpItemAbbr", fg=fg),
        hl("CmpItemAbbrMatch", fg=c["accent"], bold=True),
        hl("CmpItemAbbrMatchFuzzy", fg=c["accent"]),
        hl("CmpItemKind", fg=c["muted"]),
        hl("CmpItemMenu", fg=c["muted"]),
        hl("CmpItemKindSnippet", fg=c["mauve"]),
        hl("CmpItemKindKeyword", fg=c["accent"]),
        hl("CmpItemKindText", fg=fg),
        hl("CmpItemKindMethod", fg=c["accent_2"]),
        hl("CmpItemKindFunction", fg=c["accent_2"]),
        hl("CmpItemKindConstructor", fg=c["accent"]),
        hl("CmpItemKindField", fg=c["diagnostic"]),
        hl("CmpItemKindVariable", fg=c["mauve"]),
        hl("CmpItemKindClass", fg=c["diagnostic"]),
        hl("CmpItemKindInterface", fg=c["diagnostic"]),
        hl("CmpItemKindModule", fg=c["diagnostic"]),
        hl("CmpItemKindProperty", fg=c["diagnostic"]),
        hl("CmpItemKindUnit", fg=c["sage"]),
        hl("CmpItemKindValue", fg=c["mauve"]),
        hl("CmpItemKindEnum", fg=c["diagnostic"]),
        hl("CmpItemKindEnumMember", fg=c["mauve"]),
        hl("CmpItemKindKeyword", fg=c["accent"]),
        hl("CmpItemKindColor", fg=c["lavender"]),
        hl("CmpItemKindFile", fg=fg),
        hl("CmpItemKindReference", fg=c["accent_2"]),
        hl("CmpItemKindFolder", fg=c["diagnostic"]),
        hl("CmpItemKindEvent", fg=c["warning"]),
        hl("CmpItemKindOperator", fg=c["accent_2"]),
        hl("CmpItemKindTypeParameter", fg=c["diagnostic"]),
        hl("CmpItemKindCopied", fg=c["sage"]),
        "",
    ]

    return "\n".join(lines)


# ── Zsh-syntax-highlighting ──────────────────────────────────────


def zsh_syntax_content(c: dict[str, str]) -> str:
    """Return a Zsh syntax-highlighting theme snippet."""
    mode = "dark" if c["details"] == "darker" else "light"
    bg = c["bg"]

    def g(color: str) -> str:
        return guard(c[color], bg, mode)

    return f"""# ========================================================
# {c['name']} — Zsh-syntax-highlighting theme
# Source this from .zshrc AFTER zsh-syntax-highlighting plugin.
# ========================================================

typeset -A ZSH_HIGHLIGHT_STYLES

# Main
ZSH_HIGHLIGHT_STYLES[default]='fg={g("text")}'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg={g("error")}'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg={g("accent")},bold'
ZSH_HIGHLIGHT_STYLES[alias]='fg={g("accent_2")}'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg={g("accent_2")}'
ZSH_HIGHLIGHT_STYLES[builtin]='fg={g("accent")}'
ZSH_HIGHLIGHT_STYLES[function]='fg={g("accent_2")}'
ZSH_HIGHLIGHT_STYLES[command]='fg={g("accent")}'
ZSH_HIGHLIGHT_STYLES[precommand]='fg={g("accent")},italic'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg={g("muted")}'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg={g("accent")}'

# Paths
ZSH_HIGHLIGHT_STYLES[path]='fg={g("diagnostic")}'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg={g("accent")}'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg={g("diagnostic")},underline'
ZSH_HIGHLIGHT_STYLES[path_approx]='fg={g("warning")},underline'

# Globbing
ZSH_HIGHLIGHT_STYLES[globbing]='fg={g("lavender")}'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg={g("lavender")}'

# Quoting & Brackets
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg={g("diagnostic")}'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg={g("diagnostic")}'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg={g("sage")}'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg={g("sage")}'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg={g("sage")}'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg={g("sage")}'
ZSH_HIGHLIGHT_STYLES[rc-quote]='fg={g("mauve")}'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg={g("mauve")}'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg={g("mauve")}'
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg={g("mauve")}'
ZSH_HIGHLIGHT_STYLES[assign]='fg={g("text")}'
ZSH_HIGHLIGHT_STYLES[redirection]='fg={g("accent_2")}'
ZSH_HIGHLIGHT_STYLES[comment]='fg={g("comment")},italic'
ZSH_HIGHLIGHT_STYLES[variable]='fg={g("mauve")}'
ZSH_HIGHLIGHT_STYLES[mathvar]='fg={g("mauve")}'
ZSH_HIGHLIGHT_STYLES[null]='fg={g("muted")}'

# Brackets
ZSH_HIGHLIGHT_STYLES[bracket-level-1]='fg={g("accent")}'
ZSH_HIGHLIGHT_STYLES[bracket-level-2]='fg={g("diagnostic")}'
ZSH_HIGHLIGHT_STYLES[bracket-level-3]='fg={g("sage")}'
ZSH_HIGHLIGHT_STYLES[bracket-level-4]='fg={g("lavender")}'

# Cursor
ZSH_HIGHLIGHT_STYLES[cursor-matchingbracket]='fg={bg},bg={g("accent")}'
"""


# ── LS_COLORS / eza ──────────────────────────────────────────────


def ls_colors_content(c: dict[str, str]) -> str:
    """Return a shell snippet exporting LS_COLORS for Dreamcoder."""
    mode = "dark" if c["details"] == "darker" else "light"
    bg = c["bg"]

    def g(color: str) -> str:
        return guard(c[color], bg, mode)

    # Convert hex colors to 24-bit ANSI escape sequences
    def ansi_fg(hex_color: str) -> str:
        r, g_, b = int(hex_color[1:3], 16), int(hex_color[3:5], 16), int(hex_color[5:7], 16)
        return f"38;2;{r};{g_};{b}"

    def ansi_bg(hex_color: str) -> str:
        r, g_, b = int(hex_color[1:3], 16), int(hex_color[3:5], 16), int(hex_color[5:7], 16)
        return f"48;2;{r};{g_};{b}"

    fg_text = ansi_fg(g("text"))
    fg_dir = ansi_fg(g("accent"))
    fg_link = ansi_fg(g("diagnostic"))
    fg_exe = ansi_fg(g("accent_2"))
    fg_img = ansi_fg(g("mauve"))
    fg_archive = ansi_fg(g("lavender"))
    fg_doc = ansi_fg(g("muted"))
    fg_socket = ansi_fg(g("sage"))
    fg_pipe = ansi_fg(g("warning"))
    fg_block = ansi_fg(g("error"))
    fg_warning = ansi_fg(g("warning"))
    fg_error = ansi_fg(g("error"))
    bg_or = ansi_bg(bg)

    return f"""# ========================================================
# {c['name']} — LS_COLORS / eza theme
# ========================================================
# Source this from .zshrc or .bashrc.
# These are 24-bit truecolor codes — ensure TERM supports it.

# Core file types
export LS_COLORS="\\
  di={fg_dir}:\\
  ex={fg_exe}:\\
  ln={fg_link}:\\
  or={bg_or};{fg_text}:\\
  so={fg_socket}:\\
  pi={fg_pipe}:\\
  bd={fg_block}:\\
  cd={fg_block}:\\
  su={bg_or};{fg_exe}:\\
  sg={bg_or};{fg_exe}:\\
  tw={fg_dir};{ansi_bg(c["surface0"])}:\\
  ow={fg_dir};{ansi_bg(c["surface0"])}:\\
  st={fg_dir};{ansi_bg(c["surface1"])}:\\
  *.tar={fg_archive}:\\
  *.tgz={fg_archive}:\\
  *.gz={fg_archive}:\\
  *.bz2={fg_archive}:\\
  *.xz={fg_archive}:\\
  *.zst={fg_archive}:\\
  *.zip={fg_archive}:\\
  *.7z={fg_archive}:\\
  *.rar={fg_archive}:\\
  *.iso={fg_archive}:\\
  *.dmg={fg_archive}:\\
  *.jpg={fg_img}:\\
  *.jpeg={fg_img}:\\
  *.png={fg_img}:\\
  *.gif={fg_img}:\\
  *.bmp={fg_img}:\\
  *.svg={fg_img}:\\
  *.webp={fg_img}:\\
  *.ico={fg_img}:\\
  *.mp3={fg_img}:\\
  *.wav={fg_img}:\\
  *.flac={fg_img}:\\
  *.ogg={fg_img}:\\
  *.m4a={fg_img}:\\
  *.mp4={fg_img}:\\
  *.mkv={fg_img}:\\
  *.webm={fg_img}:\\
  *.mov={fg_img}:\\
  *.pdf={fg_doc}:\\
  *.doc={fg_doc}:\\
  *.docx={fg_doc}:\\
  *.odt={fg_doc}:\\
  *.xls={fg_doc}:\\
  *.xlsx={fg_doc}:\\
  *.ppt={fg_doc}:\\
  *.pptx={fg_doc}:\\
  *.txt={fg_doc}:\\
  *.md={g("accent")}:\\
  *.cfg={fg_doc}:\\
  *.conf={fg_doc}:\\
  *.json={fg_doc}:\\
  *.yaml={fg_doc}:\\
  *.yml={fg_doc}:\\
  *.toml={fg_doc}:\\
  *.xml={fg_doc}:\\
  *.sh={fg_exe}:\\
  *.bash={fg_exe}:\\
  *.zsh={fg_exe}:\\
  *.fish={fg_exe}:\\
  *.py={fg_exe}:\\
  *.rb={fg_exe}:\\
  *.rs={fg_exe}:\\
  *.go={fg_exe}:\\
  *.ts={fg_exe}:\\
  *.js={fg_exe}:\\
  *.css={fg_doc}:\\
  *.html={fg_doc}:\\
  *.c={fg_doc}:\\
  *.h={fg_doc}:\\
  *.cpp={fg_doc}:\\
  *.hpp={fg_doc}:\\
  *.swp={fg_doc}:\\
  *.swo={fg_doc}:\\
  *.bak={fg_doc}:\\
  *.orig={fg_doc}:\\
"

# eza (modern ls replacement) additional config
export EZA_COLORS="\\
  di={fg_dir}:\\
  ex={fg_exe}:\\
  ln={fg_link}:\\
  so={fg_socket}:\\
  pi={fg_pipe}:\\
  bd={fg_block}:\\
  cd={fg_block}:\\
  uw={fg_warning}:\\
  ux={fg_error}:\\
  gwx={fg_warning}:\\
  *.md={g("accent")}:\\
"
"""


# ── Bat (syntax-highlighted pager) ────────────────────────────


def bat_content(c: dict[str, str]) -> str:
    """Return a Bat theme config snippet.

    Bat uses .tmTheme files for syntax highlighting. We generate
    those separately (see codex_tmtheme_content). This snippet
    configures Bat to use the matching Dreamcoder theme.
    """
    mode_name = "dark" if c["details"] == "darker" else "light"
    bg = c["bg"]
    text = c["text"]
    muted = c["muted"]
    accent = c["accent"]

    return f"""# ========================================================
# {c['name']} — Bat theme
# ========================================================
# Set the --theme to use the Dreamcoder tmTheme.
# Install: bat cache --build (after placing .tmTheme in Bat themes dir)
#
# Recommended approach:
#   1. Symlink or copy the Codex-CLI Dreamcoder.tmTheme to Bat themes:
#      ln -sf "$DREAMCODER_DOTS_DIR/Codex-CLI/Dreamcoder-Dark.tmTheme" \\
#             "$(bat --config-dir)/themes/Dreamcoder-Dark.tmTheme"
#   2. Set this in your shell config:
#      export BAT_THEME="Dreamcoder-Dark"

export BAT_THEME="Dreamcoder-{'Dark' if mode_name == 'dark' else 'Light'}"

# Fallback: if no .tmTheme is installed, at least style the pager chrome
# with Dreamcoder colors via bat's --style and command-line flags.
export BAT_STYLE="header,numbers,changes,grid"
export BAT_TABS="4"

# Syntax theme can also be set via environment variable
# BAT_THEME="Dreamcoder-Dark"  # or -Light / -Dusk
"""


# ── Delta (git diff viewer) ────────────────────────────────────


def delta_content(c: dict[str, str]) -> str:
    """Return a Git Delta config snippet with Dreamcoder colors."""
    mode = "dark" if c["details"] == "darker" else "light"
    bg = c["bg"]

    def g(color: str) -> str:
        return guard(c[color], bg, mode)

    plus_bg = mix(c["sage"], bg, 0.85)
    minus_bg = mix(c["error"], bg, 0.85)

    return f"""# ========================================================
# {c['name']} — Git Delta theme
# ========================================================
# Include from ~/.config/git/config:
#   [include]
#       path = ~/.config/git/delta-dreamcoder.gitconfig

[delta]
    # Syntax highlighting theme for diff content
    syntax-theme = Dreamcoder-{'Dark' if mode == 'dark' else 'Light'}

    # Line colors
    plus-color = "{plus_bg}"
    minus-color = "{minus_bg}"
    plus-emph-color = "{g('sage')}"
    minus-emph-color = "{g('error')}"

    # Diff UI
    file-style = "{g('accent')}"
    file-decoration-style = "bold yellow box ul"
    hunk-header-style = "file line-number syntax"
    hunk-header-decoration-style = "yellow box"
    hunk-header-file-style = "{g('accent')}"
    hunk-header-line-number-style = "#{g('muted')}"
    hunk-header-color = "{mix(g('muted'), bg, 0.85)}"

    # Commit decorations
    commit-style = "{g('accent')} bold"
    commit-decoration-style = "bold yellow box ul"

    # Line numbers
    line-numbers = true
    line-numbers-left-style = "{g('muted')}"
    line-numbers-right-style = "{g('muted')}"
    line-numbers-minus-style = "{g('error')}"
    line-numbers-plus-style = "{g('sage')}"

    # Side-by-side
    side-by-side = true

    # Whitespace highlighting
    whitespace-error-style = "{g('warning')}"

    # Navigation
    navigate = true
"""


# ── Fzf ────────────────────────────────────────────────────────


def fzf_content(c: dict[str, str]) -> str:
    """Return a FZF_DEFAULT_OPTS export with Dreamcoder colors."""
    mode = "dark" if c["details"] == "darker" else "light"
    bg = c["bg"]
    # Guard text/foreground colors against background
    # UI/background colors are used raw from the palette
    fg_text = guard(c["text"], bg, mode)

    return f"""# ========================================================
# {c['name']} — Fzf theme
# ========================================================
# Source this from .zshrc or .bashrc.

export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS"'
  --color=bg:{c['bg']}
  --color=bg+:{c['surface0']}
  --color=fg:{fg_text}
  --color=fg+:{fg_text}
  --color=hl:{c['accent']}
  --color=hl+:{c['accent']}
  --color=info:{c['diagnostic']}
  --color=marker:{c['sage']}
  --color=prompt:{c['accent']}
  --color=spinner:{c['lavender']}
  --color=pointer:{c['accent_2']}
  --color=header:{c['muted']}
  --color=border:{c['border']}
  --color=label:{c['muted']}
  --color=query:{fg_text}
  --color=gutter:{c['bg']}
  --color=scrollbar:{c['border']}
  --color=separator:{c['border']}
  --color=preview-bg:{c['bg']}
  --color=preview-border:{c['border']}
'
"""


# ── Btop ────────────────────────────────────────────────────────


def btop_content(c: dict[str, str]) -> str:
    """Return a Btop theme file."""
    mode = "dark" if c["details"] == "darker" else "light"
    bg = c["bg"]
    # Guard foreground text colors; use raw palette for backgrounds/surfaces
    txt = guard(c["text"], bg, mode)
    mtd = guard(c["muted"], bg, mode)
    acc = guard(c["accent"], bg, mode)
    acc2 = guard(c["accent_2"], bg, mode)
    diag = guard(c["diagnostic"], bg, mode)
    sage = guard(c["sage"], bg, mode)
    lav = guard(c["lavender"], bg, mode)
    mauve = guard(c["mauve"], bg, mode)
    err = guard(c["error"], bg, mode)
    warn = guard(c["warning"], bg, mode)
    sel_bg = c["selection"]

    return f"""# ========================================================
# {c['name']} — Btop theme
# ========================================================
# Place in ~/.config/btop/themes/ and select from Btop UI.

theme[main_bg]="{c['bg']}"
theme[main_fg]="{txt}"
theme[title]="{acc}"
theme[hi_fg]="{acc}"
theme[selected_bg]="{sel_bg}"
theme[selected_fg]="{txt}"
theme[inactive_fg]="{mtd}"
theme[graph_line]="{c['border']}"
theme[proc_misc]="{mtd}"
theme[cpu_core]="{diag}"
theme[mem_free]="{sage}"
theme[mem_used]="{acc2}"
theme[mem_cached]="{diag}"
theme[user_bg]="{c['surface0']}"
theme[user_fg]="{txt}"
theme[temp]="{warn}"
theme[disk]="{diag}"
theme[process]="{lav}"
theme[process_selected]="{acc}"
theme[core_bar]="{acc}"
theme[temp_bar]="{warn}"
theme[swap]="{mauve}"
theme[div_line]="{c['border']}"
theme[process_bg]="{c['surface0']}"
theme[process_fg]="{txt}"
theme[bad]="{err}"
theme[good]="{sage}"
theme[widget_bg]="{c['surface0']}"
theme[widget_fg]="{txt}"
theme[widget_border]="{c['border']}"
theme[widget_selected]="{acc}"
theme[graph_bg]="{c['surface0']}"
theme[graph_fg]="{txt}"
theme[graph_high]="{acc2}"
theme[graph_low]="{diag}"
theme[graph_med]="{acc}"
theme[proc_bg]="{c['surface0']}"
theme[proc_fg]="{txt}"
theme[process_border]="{c['border']}"
theme[widget_title]="{acc}"
theme[box_border]="{c['border']}"
theme[box_bg]="{c['surface0']}"
theme[box_fg]="{txt}"
theme[box_selected]="{acc}"
theme[os_bg]="{c['surface0']}"
theme[os_fg]="{txt}"
theme[clock_bg]="{c['surface0']}"
theme[clock_fg]="{acc}"
theme[bat_high]="{sage}"
theme[bat_med]="{warn}"
theme[bat_low]="{err}"
theme[sensor_bg]="{c['surface0']}"
theme[sensor_fg]="{txt}"
theme[sensor_bar_bg]="{c['surface1']}"
theme[sensor_bar_fg]="{acc}"
theme[net_bg]="{c['surface0']}"
theme[net_fg]="{txt}"
theme[net_download]="{sage}"
theme[net_upload]="{acc2}"
"""


# ── Dunst (notification daemon) ───────────────────────────────


def dunst_content(c: dict[str, str]) -> str:
    """Return a Dunst config snippet with Dreamcoder colors."""
    mode = "dark" if c["details"] == "darker" else "light"
    bg = c["bg"]
    # Guard foreground text against notification background
    txt = guard(c["text"], bg, mode)
    mtd = guard(c["muted"], bg, mode)
    acc = guard(c["accent"], bg, mode)
    err = guard(c["error"], bg, mode)
    # Background colors kept raw (notification backgrounds)
    urgent_bg = mix(c["error"], bg, 0.70)
    border = c["border"]
    border_ui = c["border_ui"]

    return f"""# ========================================================
# {c['name']} — Dunst theme
# ========================================================
# Include from dunstrc:
#   [include] dreamcoder-dunst.conf

[urgency_low]
    background = "{c['bg']}"
    foreground = "{txt}"
    highlight = "{acc}"
    frame_color = "{border}"

[urgency_normal]
    background = "{c['surface0']}"
    foreground = "{txt}"
    highlight = "{acc}"
    frame_color = "{border_ui}"

[urgency_critical]
    background = "{urgent_bg}"
    foreground = "{txt}"
    highlight = "{err}"
    frame_color = "{err}"
"""


# ── Firefox userChrome.css ─────────────────────────────────────


def firefox_content(c: dict[str, str]) -> str:
    """Return a Firefox userChrome.css with Dreamcoder colors."""
    mode = "dark" if c["details"] == "darker" else "light"
    bg = c["bg"]
    surface0 = c["surface0"]
    surface1 = c["surface1"]

    # Guard foreground/text colors against background
    txt = guard(c["text"], bg, mode)
    mtd = guard(c["muted"], bg, mode)
    acc = guard(c["accent"], bg, mode)
    acc2 = guard(c["accent_2"], bg, mode)

    # Background and UI colors - raw from palette
    hover_bg = mix(c["accent"], bg, 0.85)
    active_bg = mix(c["accent"], bg, 0.75)
    input_bg = surface0 if mode == "dark" else surface1
    toolbar_bg = surface0 if mode == "dark" else c["bg_soft"]

    return f"""/* ========================================================
   {c['name']} — Firefox userChrome.css
   ========================================================
   Place in ~/.mozilla/firefox/*.default-release/chrome/userChrome.css
   Requires toolkit.legacyUserProfileCustomizations.stylesheets = true
   in about:config. */

:root {{
  --dreamcoder-bg: {bg};
  --dreamcoder-surface: {surface0};
  --dreamcoder-surface-1: {surface1};
  --dreamcoder-text: {txt};
  --dreamcoder-text-dim: {mtd};
  --dreamcoder-accent: {acc};
  --dreamcoder-accent-2: {acc2};
  --dreamcoder-border: {c['border']};
  --dreamcoder-border-ui: {c['border_ui']};
  --dreamcoder-error: {c['error']};
  --dreamcoder-warning: {c['warning']};
  --dreamcoder-sage: {c['sage']};
  --dreamcoder-input-bg: {input_bg};
  --dreamcoder-toolbar-bg: {toolbar_bg};
  --dreamcoder-hover: {hover_bg};
  --dreamcoder-active: {active_bg};
}}

/* Main window */
#main-window,
#navigator-toolbox {{
  background-color: var(--dreamcoder-bg) !important;
  color: var(--dreamcoder-text) !important;
}}

/* Toolbar & URL bar */
#nav-bar,
#nav-bar toolbarbutton,
#urlbar,
#urlbar-background {{
  background-color: var(--dreamcoder-toolbar-bg) !important;
  color: var(--dreamcoder-text) !important;
  border-color: var(--dreamcoder-border) !important;
}}

#urlbar[focused="true"] > #urlbar-background {{
  border-color: var(--dreamcoder-accent) !important;
}}

/* Sidebar (bookmarks, history) */
#sidebar-box,
#sidebar {{
  background-color: var(--dreamcoder-bg) !important;
  color: var(--dreamcoder-text) !important;
}}

.sidebar-placesTreechildren {{
  color: var(--dreamcoder-text) !important;
}}

/* Tab bar */
#TabsToolbar,
#tabbrowser-tabs,
.tab-background {{
  background-color: var(--dreamcoder-bg) !important;
}}

.tabbrowser-tab:not([selected]) .tab-background {{
  background-color: var(--dreamcoder-surface) !important;
}}

.tabbrowser-tab[selected] .tab-background {{
  background-color: var(--dreamcoder-toolbar-bg) !important;
  border-color: var(--dreamcoder-accent) !important;
}}

.tabbrowser-tab .tab-label {{
  color: var(--dreamcoder-text-dim) !important;
}}

.tabbrowser-tab[selected] .tab-label {{
  color: var(--dreamcoder-text) !important;
}}

/* Context menus */
menupopup,
popup {{
  background-color: var(--dreamcoder-bg) !important;
  color: var(--dreamcoder-text) !important;
}}

menuitem {{
  color: var(--dreamcoder-text) !important;
}}

menuitem:hover {{
  background-color: var(--dreamcoder-hover) !important;
  color: var(--dreamcoder-text) !important;
}}

/* Status panel */
#statuspanel-label {{
  background-color: var(--dreamcoder-bg) !important;
  color: var(--dreamcoder-text-dim) !important;
  border-color: var(--dreamcoder-border) !important;
}}

/* Find bar */
#findbar {{
  background-color: var(--dreamcoder-bg) !important;
  color: var(--dreamcoder-text) !important;
}}

#findbar input {{
  background-color: var(--dreamcoder-input-bg) !important;
  color: var(--dreamcoder-text) !important;
  border-color: var(--dreamcoder-border) !important;
}}

/* Private browsing indicators */
#private-browsing-indicator-with-label {{
  color: var(--dreamcoder-accent-2) !important;
}}

/* Downloads panel */
#downloadsPanel,
#downloadsListBox {{
  background-color: var(--dreamcoder-bg) !important;
  color: var(--dreamcoder-text) !important;
}}

/* Scrollbar styling */
:root {{
  scrollbar-color: var(--dreamcoder-border) var(--dreamcoder-bg) !important;
}}

* {{
  scrollbar-width: thin !important;
  scrollbar-color: var(--dreamcoder-border) var(--dreamcoder-bg) !important;
}}
"""


# ── Obsidian CSS Snippet ────────────────────────────────────────


def obsidian_content(c: dict[str, str]) -> str:
    """Return an Obsidian CSS snippet with Dreamcoder colors."""
    mode = "dark" if c["details"] == "darker" else "light"
    bg = c["bg"]

    is_dark = mode == "dark"
    class_prefix = ".theme-dark" if is_dark else ".theme-light"

    return f"""/* ========================================================
   {c['name']} — Obsidian CSS snippet
   ========================================================
   Place in your vault's .obsidian/snippets/ folder.
   Enable in Settings → Appearance → CSS snippets. */

{class_prefix} {{
  /* Base — raw palette colors for backgrounds and surfaces */
  --background-primary: {c['bg']};
  --background-primary-alt: {c['surface0']};
  --background-secondary: {c['surface0']};
  --background-secondary-alt: {c['surface1']};
  --background-modifier-border: {c['border']};
  --background-modifier-border-hover: {c['border_ui']};
  --background-modifier-form-field: {c['surface0']};
  --background-modifier-success: {mix(c['sage'], bg, 0.75)};
  --background-modifier-error: {mix(c['error'], bg, 0.75)};
  --background-modifier-message: {c['surface1']};

  /* Text — guarded against background for accessibility */
  --text-normal: {c['text']};
  --text-muted: {c['muted']};
  --text-faint: {c['subtle']};
  --text-accent: {c['accent']};
  --text-accent-hover: {c['accent_2']};
  --text-error: {c['error']};
  --text-warning: {c['warning']};
  --text-success: {c['sage']};
  --text-selection: {mix(c['selection'], bg, 0.5)};
  --text-on-accent: {c['bg']};

  /* Interactive */
  --interactive-normal: {c['surface1']};
  --interactive-hover: {c['surface2']};
  --interactive-accent: {c['accent']};
  --interactive-accent-hover: {c['accent_2']};
  --interactive-success: {c['sage']};

  /* Scrollbar */
  --scrollbar-bg: transparent;
  --scrollbar-thumb-bg: {c['border']};
  --scrollbar-active-thumb-bg: {c['border_ui']};

  /* Code — syntax highlighting colors */
  --code-normal: {c['text']};
  --code-comment: {c['comment']};
  --code-punctuation: {c['muted']};
  --code-keyword: {c['accent']};
  --code-operator: {c['accent_2']};
  --code-function: {c['accent_2']};
  --code-string: {c['sage']};
  --code-number: {c['mauve']};
  --code-tag: {c['accent']};
  --code-important: {c['error']};
  --code-background: {c['surface0']};

  /* Heading */
  --h1-color: {c['accent']};
  --h2-color: {c['accent']};
  --h3-color: {c['accent_2']};
  --h4-color: {c['diagnostic']};
  --h5-color: {c['muted']};
  --h6-color: {c['subtle']};

  /* Link */
  --link-color: {c['accent']};
  --link-color-hover: {c['accent_2']};
  --link-external-color: {c['diagnostic']};
  --link-external-color-hover: {c['accent_2']};

  /* Checkbox */
  --checkbox-color: {c['accent']};
  --checkbox-color-hover: {c['accent_2']};
  --checkbox-border-color: {c['border']};
  --checkbox-mark-color: {c['bg']};

  /* Table */
  --table-header-background: {c['surface1']};
  --table-header-background-hover: {c['surface2']};
  --table-row-background-hover: {c['surface0']};
  --table-border-color: {c['border']};

  /* Graph */
  --graph-line: {c['border']};
  --graph-node: {c['muted']};
  --graph-node-focused: {c['accent']};
  --graph-node-tag: {c['diagnostic']};
  --graph-node-attachment: {c['sage']};
}}

/* Headings */
.markdown-rendered h1 {{ color: var(--h1-color); }}
.markdown-rendered h2 {{ color: var(--h2-color); }}
.markdown-rendered h3 {{ color: var(--h3-color); }}
.markdown-rendered h4 {{ color: var(--h4-color); }}
.markdown-rendered h5 {{ color: var(--h5-color); }}
.markdown-rendered h6 {{ color: var(--h6-color); }}

/* Tags */
.tag {{
  background-color: {mix(c['accent'], bg, 0.85)};
  color: {c['accent']};
  border-radius: 4px;
  padding: 0 6px;
}}

/* Blockquotes */
blockquote {{
  border-color: {c['accent']} !important;
}}

/* Search highlights */
.search-result-file-matched-text,
.is-selected .search-result-file-matched-text,
mark {{
  background-color: {mix(c['accent'], bg, 0.80)} !important;
  color: {c['bg']} !important;
}}

/* Active line in edit mode */
.cm-active {{
  background-color: {c['surface0']} !important;
}}

/* Selection */
::selection {{
  background-color: {mix(c['selection'], bg, 0.45)} !important;
}}

/* Tooltip */
.tooltip {{
  background-color: {c['surface1']} !important;
  color: {c['text']} !important;
}}

/* Menu */
.menu {{
  background-color: {c['surface0']} !important;
}}

.menu-item:hover {{
  background-color: {c['surface1']} !important;
}}
"""


# ── Cava (audio visualizer) ──────────────────────────────────────


def cava_content(c: dict[str, str]) -> str:
    """Return a Cava config snippet with Dreamcoder colors."""
    mode = "dark" if c["details"] == "darker" else "light"
    bg = c["bg"]

    return f"""# ========================================================
# {c['name']} — Cava theme
# ========================================================
# Include from ~/.config/cava/config or place in
# ~/.config/cava/dreamcoder-cava.config.

[color]
# Background
background = '{c['bg']}'

# Gradient mode for smooth transitions
gradient = 1
gradient_count = 8

# Gradient colors (low to high frequency) — raw palette, muted at lower end
gradient_color_1 = '{mix(c['diagnostic'], bg, 0.60)}'
gradient_color_2 = '{mix(c['diagnostic'], bg, 0.40)}'
gradient_color_3 = '{mix(c['accent'], bg, 0.50)}'
gradient_color_4 = '{mix(c['accent'], bg, 0.30)}'
gradient_color_5 = '{c['accent']}'
gradient_color_6 = '{c['accent_2']}'
gradient_color_7 = '{mix(c['error'], bg, 0.30)}'
gradient_color_8 = '{c['error']}'

# Mono color (used when gradient = 0)
foreground = '{c['accent']}'
"""


# ── Public API ──────────────────────────────────────────────────


_EXTRA_RENDERERS = {
    "nvim": nvim_content,
    "zsh_syntax": zsh_syntax_content,
    "ls_colors": ls_colors_content,
    "bat": bat_content,
    "delta": delta_content,
    "fzf": fzf_content,
    "btop": btop_content,
    "dunst": dunst_content,
    "firefox": firefox_content,
    "obsidian": obsidian_content,
    "cava": cava_content,
}

__all__ = list(_EXTRA_RENDERERS.keys()) + ["_EXTRA_RENDERERS"]
