"""Focused extra Dreamcoder theme renderers."""

from __future__ import annotations

from .palette import guard, mix

from .renderers_extra_nvim_lsp import nvim_lsp_groups
from .renderers_extra_nvim_plugins import nvim_plugin_groups
from .renderers_extra_nvim_syntax import nvim_syntax_groups
from .renderers_extra_nvim_ui import nvim_ui_groups


def nvim_content(c: dict[str, str]) -> str:
    """Return a Neovim Lua colorscheme using the Dreamcoder palette."""

    def hl(name, **kwargs):
        parts = []
        if "fg" in kwargs:
            parts.append(f'    fg = "{kwargs["fg"]}"')
        if "bg" in kwargs:
            parts.append(f'    bg = "{kwargs["bg"]}"')
        if "sp" in kwargs:
            parts.append(f'    sp = "{kwargs["sp"]}"')
        if "bold" in kwargs and kwargs["bold"]:
            parts.append("    bold = true")
        if "italic" in kwargs and kwargs["italic"]:
            parts.append("    italic = true")
        if "underline" in kwargs and kwargs["underline"]:
            parts.append("    underline = true")
        if "undercurl" in kwargs and kwargs["undercurl"]:
            parts.append("    undercurl = true")
        if "strikethrough" in kwargs and kwargs["strikethrough"]:
            parts.append("    strikethrough = true")
        if "reverse" in kwargs and kwargs["reverse"]:
            parts.append("    reverse = true")
        inner = ",\n".join(parts)
        return f'  vim.api.nvim_set_hl(0, "{name}", {{\n{inner}\n  }})\n'

    invert = c["details"] == "lighter"
    bg = c["bg"]
    normal_bg = bg if invert else "none"
    text = c["text"]
    fg = text
    # Use surface1 for selection background in all modes - better visibility
    sel_bg = c["surface1"]
    sel_fg = c["text"]

    lines = [
        f"""-- ========================================================
-- {c["name"]} — generated by Dreamcoder sync
-- ========================================================
-- Usage: vim.cmd.colorscheme("dreamcoder")
-- ========================================================

vim.g.colors_name = "dreamcoder"

-- Glass blur stays dark-only; light needs opaque paper backgrounds for readability.
vim.opt.winblend = 10
vim.opt.pumblend = 10

local c = {{
  bg        = "{bg}",
  surface0  = "{c["surface0"]}",
  surface1  = "{c["surface1"]}",
  surface2  = "{c["surface2"]}",
  text      = "{text}",
  muted     = "{c["muted"]}",
  subtle    = "{c["subtle"]}",
  comment   = "{c["comment"]}",
  accent    = "{c["accent"]}",
  accent2   = "{c["accent_2"]}",
  diagnostic = "{c["diagnostic"]}",
  sage      = "{c["sage"]}",
  lavender  = "{c["lavender"]}",
  mauve     = "{c["mauve"]}",
  error     = "{c["error"]}",
  warning   = "{c["warning"]}",
  border    = "{c["border"]}",
  border_ui = "{c["border_ui"]}",
  selection = "{sel_bg}",
}}

local function h(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end

-- ── Editor UI ────────────────────────────────────────────────
-- Normal background is opaque in light so dark terminal transparency cannot hide text.
-- Dark mode keeps transparent Normal for Ember Noir glass.
""",
    ]
    group_args = (hl, c, fg, bg, sel_fg, sel_bg)
    lines.extend(nvim_ui_groups(hl, c, fg, bg, sel_fg, sel_bg, normal_bg))
    lines.extend(nvim_syntax_groups(*group_args))
    lines.extend(nvim_lsp_groups(*group_args))
    lines.extend(nvim_plugin_groups(*group_args))

    return "\n".join(lines)
