"""Neovim highlight group chunks for Dreamcoder."""

from __future__ import annotations

from typing import Callable

from .palette import mix


Hl = Callable[..., str]


def nvim_ui_groups(hl: Hl, c: dict[str, str], fg: str, bg: str, sel_fg: str, sel_bg: str) -> list[str]:
    return [
        hl("Normal", fg=fg, bg="none"),
        hl("NormalFloat", fg=fg, bg=c["surface0"]),
        hl("FloatBorder", fg=c["border_ui"], bg=c["surface0"]),
        hl("NonText", fg=c["subtle"]),
        hl("SpecialKey", fg=c["muted"]),
        hl("Whitespace", fg=c["border"]),
        hl("EndOfBuffer", fg="none"),
        hl("Cursor", fg=bg, bg=c["accent"]),
        hl("lCursor", fg=bg, bg=c["accent"]),
        hl("CursorLine", bg=c["surface0"]),
        hl("CursorLineNr", fg=c["accent"], bold=True),
        hl("LineNr", fg=c["muted"]),
        hl("CursorColumn", bg=c["surface0"]),
        hl("ColorColumn", bg=c["surface0"]),
        hl("SignColumn", bg="none"),
        "",
        "  -- ── Selection & Search ───────────────────────────────",
        hl("Visual", fg=sel_fg, bg=sel_bg),
        hl("VisualNOS", fg=sel_fg, bg=sel_bg),
        hl("Search", fg=bg, bg=c["accent"]),
        hl("IncSearch", fg=bg, bg=c["accent_2"]),
        hl("CurSearch", fg=bg, bg=c["accent"]),
        hl("Substitute", fg=bg, bg=c["accent_2"]),
        hl("MatchParen", fg=c["accent_2"], bold=True),
        "",
        "  -- ── Popup Menu ────────────────────────────────────────",
        hl("Pmenu", fg=c["muted"], bg=c["surface1"]),
        hl("PmenuSel", fg=bg, bg=c["accent"]),
        hl("PmenuSbar", bg=c["surface2"]),
        hl("PmenuThumb", bg=c["muted"]),
        "",
        "  -- ── Statusline & Winbar ───────────────────────────────",
        hl("StatusLine", fg=fg, bg=c["surface1"]),
        hl("StatusLineNC", fg=c["muted"], bg=c["surface0"]),
        hl("StatusLineTerm", fg=fg, bg=c["surface1"]),
        hl("StatusLineTermNC", fg=c["muted"], bg=c["surface0"]),
        hl("WinBar", fg=fg, bg=c["surface1"]),
        hl("WinBarNC", fg=c["muted"], bg=c["surface0"]),
        hl("WinSeparator", fg=c["border"]),
        "",
        "  -- ── Tabline ────────────────────────────────────────────",
        hl("TabLine", fg=c["muted"], bg=c["surface0"]),
        hl("TabLineSel", fg=fg, bg=c["surface1"]),
        hl("TabLineFill", bg=bg),
        "",
        "  -- ── Folds ─────────────────────────────────────────────",
        hl("Folded", fg=c["muted"], bg=c["surface0"]),
        hl("FoldColumn", fg=c["muted"]),
        "",
        "  -- ── Diff ──────────────────────────────────────────────",
        hl("DiffAdd", bg=mix(c["sage"], c["surface0"], 0.7)),
        hl("DiffChange", bg=mix(c["warning"], c["surface0"], 0.7)),
        hl("DiffDelete", bg=mix(c["error"], c["surface0"], 0.7)),
        hl("DiffText", bg=mix(c.get("focus", c["accent"]), c["surface0"], 0.65)),
        "",
        "  -- ── Spell ─────────────────────────────────────────────",
        hl("SpellBad", sp=c["error"], undercurl=True),
        hl("SpellCap", sp=c["warning"], undercurl=True),
        hl("SpellLocal", sp=c["diagnostic"], undercurl=True),
        hl("SpellRare", sp=c["mauve"], undercurl=True),
        "",
        "  -- ── Messages ──────────────────────────────────────────",
        hl("MsgArea", fg=fg),
        hl("ModeMsg", fg=c["accent"]),
        hl("WarningMsg", fg=c["warning"]),
        hl("ErrorMsg", fg=c["error"]),
        hl("Question", fg=c["diagnostic"]),
        "",
        "  -- ── Misc ──────────────────────────────────────────────",
        hl("Title", fg=c["accent"], bold=True),
        hl("Directory", fg=c["diagnostic"]),
        hl("Conceal", fg=c["muted"]),
        hl("TermCursor", fg=bg, bg=c["accent"]),
        "",
        "  -- ── Classic Syntax ────────────────────────────────────",
    ]
