# ========================================================
# Dreamcoder Anthracite Steel — Dunst theme
# ========================================================
# Include from dunstrc:
#   [include] dreamcoder-dunst.conf

[urgency_low]
    background = "#070A13"
    foreground = "#E6EDF3"
    highlight = "#A5C7E8"
    frame_color = "#17202B"

[urgency_normal]
    background = "#0D121A"
    foreground = "#E6EDF3"
    highlight = "#A5C7E8"
    frame_color = "#6A8497"

[urgency_critical]
    background = "#493036"
    foreground = "#E6EDF3"
    highlight = "#E38989"
    frame_color = "#E38989"
