# ========================================================
# Dreamcoder Anthracite Steel Night — Dunst theme
# ========================================================
# Include from dunstrc:
#   [include] dreamcoder-dunst.conf

[urgency_low]
    background = "#07090f"
    foreground = "#beccd8"
    highlight = "#95b5d5"
    frame_color = "#161c23"

[urgency_normal]
    background = "#0d1015"
    foreground = "#beccd8"
    highlight = "#95b5d5"
    frame_color = "#6b7e8e"

[urgency_critical]
    background = "#443135"
    foreground = "#beccd8"
    highlight = "#d48d8d"
    frame_color = "#d48d8d"
