# ========================================================
# Dreamcoder Dark Night — Dunst theme
# ========================================================
# Include from dunstrc:
#   [include] dreamcoder-dunst.conf

[urgency_low]
    background = "#000000"
    foreground = "#bcc7d5"
    highlight = "#a4afee"
    frame_color = "#6d7788"

[urgency_normal]
    background = "#050507"
    foreground = "#bcc7d5"
    highlight = "#a4afee"
    frame_color = "#6d7788"

[urgency_critical]
    background = "#462828"
    foreground = "#bcc7d5"
    highlight = "#e88484"
    frame_color = "#e88484"
