$background = rgba(070A13ff)
$error = rgba(E69AA4ff)
$error_container = rgba(0D121Aff)
$inverse_on_surface = rgba(0D121Aff)
$inverse_primary = rgba(A5C7E8ff)
$inverse_surface = rgba(E6EDF3ff)
$on_background = rgba(E6EDF3ff)
$on_error = rgba(070A13ff)
$on_error_container = rgba(E6EDF3ff)
$on_primary = rgba(070A13ff)
$on_primary_container = rgba(E6EDF3ff)
$on_primary_fixed = rgba(070A13ff)
$on_primary_fixed_variant = rgba(A5C7E8ff)
$on_secondary = rgba(070A13ff)
$on_secondary_container = rgba(E6EDF3ff)
$on_secondary_fixed = rgba(070A13ff)
$on_secondary_fixed_variant = rgba(8FAFCBff)
$on_surface = rgba(E6EDF3ff)
$on_surface_variant = rgba(A8B5C2ff)
$on_tertiary = rgba(070A13ff)
$on_tertiary_container = rgba(E6EDF3ff)
$on_tertiary_fixed = rgba(070A13ff)
$on_tertiary_fixed_variant = rgba(A5C7E8ff)
$outline = rgba(17202Bff)
$outline_variant = rgba(526575ff)
$primary = rgba(A5C7E8ff)
$primary_container = rgba(151C25ff)
$primary_fixed = rgba(A5C7E8ff)
$primary_fixed_dim = rgba(8FAFCBff)
$scrim = rgba(000000ff)
$secondary = rgba(8FAFCBff)
$secondary_container = rgba(151C25ff)
$secondary_fixed = rgba(8FAFCBff)
$secondary_fixed_dim = rgba(8FAFCBff)
$shadow = rgba(000000ff)
$source_color = rgba(A5C7E8ff)
$surface = rgba(070A13ff)
$surface_bright = rgba(0D121Aff)
$surface_container = rgba(151C25ff)
$surface_container_high = rgba(151C25ff)
$surface_container_highest = rgba(202A35ff)
$surface_container_low = rgba(0D121Aff)
$surface_container_lowest = rgba(0D121Aff)
$surface_dim = rgba(0D121Aff)
$surface_tint = rgba(A5C7E8ff)
$surface_variant = rgba(151C25ff)
$tertiary = rgba(7CB3D9ff)
$tertiary_container = rgba(0D121Aff)
$tertiary_fixed = rgba(7CB3D9ff)
$tertiary_fixed_dim = rgba(7CB3D9ff)
