$background = rgba(000000ff)
$error = rgba(e88484ff)
$error_container = rgba(050507ff)
$inverse_on_surface = rgba(050507ff)
$inverse_primary = rgba(a4afeeff)
$inverse_surface = rgba(bcc7d5ff)
$on_background = rgba(bcc7d5ff)
$on_error = rgba(000000ff)
$on_error_container = rgba(bcc7d5ff)
$on_primary = rgba(000000ff)
$on_primary_container = rgba(bcc7d5ff)
$on_primary_fixed = rgba(000000ff)
$on_primary_fixed_variant = rgba(a4afeeff)
$on_secondary = rgba(000000ff)
$on_secondary_container = rgba(bcc7d5ff)
$on_secondary_fixed = rgba(000000ff)
$on_secondary_fixed_variant = rgba(9f8ce9ff)
$on_surface = rgba(bcc7d5ff)
$on_surface_variant = rgba(8a96a7ff)
$on_tertiary = rgba(000000ff)
$on_tertiary_container = rgba(bcc7d5ff)
$on_tertiary_fixed = rgba(000000ff)
$on_tertiary_fixed_variant = rgba(3a76d6ff)
$outline = rgba(6d7788ff)
$outline_variant = rgba(6d7788ff)
$primary = rgba(a4afeeff)
$primary_container = rgba(0c0c0eff)
$primary_fixed = rgba(a4afeeff)
$primary_fixed_dim = rgba(9f8ce9ff)
$scrim = rgba(000000ff)
$secondary = rgba(9f8ce9ff)
$secondary_container = rgba(0c0c0eff)
$secondary_fixed = rgba(9f8ce9ff)
$secondary_fixed_dim = rgba(9f8ce9ff)
$shadow = rgba(000000ff)
$source_color = rgba(a4afeeff)
$surface = rgba(000000ff)
$surface_bright = rgba(050507ff)
$surface_container = rgba(0c0c0eff)
$surface_container_high = rgba(0c0c0eff)
$surface_container_highest = rgba(141418ff)
$surface_container_low = rgba(050507ff)
$surface_container_lowest = rgba(050507ff)
$surface_dim = rgba(050507ff)
$surface_tint = rgba(a4afeeff)
$surface_variant = rgba(0c0c0eff)
$tertiary = rgba(62b9e2ff)
$tertiary_container = rgba(050507ff)
$tertiary_fixed = rgba(62b9e2ff)
$tertiary_fixed_dim = rgba(62b9e2ff)
