-- ========================================================
-- Dreamcoder Neovim — entry point (LazyVim + Dreamcoder)
-- ========================================================
-- Symlink: ~/.config/nvim/init.lua → Nvim/.config/nvim/init.lua

-- Configure Node.js before loading plugins
require("config.nodejs").setup({ silent = true })

-- Bootstrap lazy.nvim, LazyVim and plugins
require("config.lazy")

-- Performance tuning
vim.opt.timeoutlen = 1000
vim.opt.ttimeoutlen = 0

-- Dreamcoder colorscheme — the single source of visual truth.
-- Generated by dreamcoder sync from tokens.json.
-- Variants: dark, light, dusk (mode-tracked via colors/dreamcoder.lua)
vim.cmd.colorscheme("dreamcoder")
