add_newline = true
palette = "wallpaper"

format = """
[](fg:surface0)\
$username\
[](bg:cream fg:surface0)\
$directory\
[](bg:lucuma fg:cream)\
$git_branch\
$git_status\
[](fg:lucuma)\
$fill\
$hostname\
$bun\
$nodejs\
$python\
$golang\
$rust\
$docker_context\
$cmd_duration\
$time
$character"""

[palettes.wallpaper]
bg = "#0e1415"
surface0 = "#252b2c"
surface1 = "#1b2122"
cream = "#dee3e4"
muted = "#bfc8ca"
beige = "#334b4f"
lucuma = "#81d3e0"
sage = "#b1cbd0"
cyan = "#b1cbd0"
lavender = "#81d3e0"
mauve = "#bac6ea"
red = "#ffb4ab"

[username]
show_always = true
style_user = "bg:surface0 fg:cream bold"
style_root = "bg:surface0 fg:red bold"
format = "[  $user ]($style)"

[hostname]
ssh_only = true
style = "fg:muted bold"
format = "[ 󰣇 $hostname ]($style) "

[directory]
style = "bg:cream fg:bg bold"
format = "[  $path ]($style)"
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = ""
style = "bg:lucuma fg:bg bold"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:lucuma fg:bg bold"
format = "[$all_status$ahead_behind ]($style)"
conflicted = "${count} "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
untracked = "?${count} "
stashed = "󰏗${count} "
modified = "~${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "✘${count} "

[fill]
symbol = " "

[bun]
symbol = ""
style = "fg:lucuma bold"
format = "[ $symbol $version]($style)"

[nodejs]
symbol = ""
style = "fg:sage bold"
format = "[ $symbol $version]($style)"

[python]
symbol = ""
style = "fg:cyan bold"
format = "[ $symbol $version]($style)"

[golang]
symbol = ""
style = "fg:lavender bold"
format = "[ $symbol $version]($style)"

[rust]
symbol = ""
style = "fg:mauve bold"
format = "[ $symbol $version]($style)"

[docker_context]
symbol = ""
style = "fg:cyan bold"
format = "[ $symbol $context]($style)"
only_with_files = true

[cmd_duration]
min_time = 1000
style = "fg:muted"
format = "[  $duration ]($style) "

[time]
disabled = false
time_format = "%H:%M:%S"
style = "fg:muted"
format = "[ ✓ $time ]($style)"

[character]
success_symbol = "[❯](bold fg:lucuma)"
error_symbol = "[✗](bold fg:red)"
vimcmd_symbol = "[❮](bold fg:sage)"

