"""Neovim highlight group chunks for Dreamcoder."""

from __future__ import annotations

from collections.abc import Callable

Hl = Callable[..., str]


def nvim_syntax_groups(
    hl: Hl, c: dict[str, str], fg: str, bg: str, sel_fg: str, sel_bg: str
) -> list[str]:
    return [
        hl("Comment", fg=c["comment"], italic=True),
        hl("Constant", fg=c["mauve"]),
        hl("String", fg=c["sage"]),
        hl("Character", fg=c["sage"]),
        hl("Number", fg=c["mauve"]),
        hl("Boolean", fg=c["lavender"]),
        hl("Float", fg=c["mauve"]),
        hl("Identifier", fg=c["muted"]),
        hl("Function", fg=c["accent_2"]),
        hl("Statement", fg=c["accent"], bold=True),
        hl("Conditional", fg=c["accent"]),
        hl("Repeat", fg=c["accent"]),
        hl("Label", fg=c["accent"]),
        hl("Operator", fg=c["accent_2"]),
        hl("Keyword", fg=c["accent"]),
        hl("Exception", fg=c["error"]),
        hl("PreProc", fg=c["subtle"]),
        hl("Include", fg=c["subtle"]),
        hl("Define", fg=c["subtle"]),
        hl("PreCondit", fg=c["subtle"]),
        hl("Type", fg=c["diagnostic"]),
        hl("StorageClass", fg=c["accent"]),
        hl("Structure", fg=c["diagnostic"]),
        hl("Typedef", fg=c["diagnostic"]),
        hl("Special", fg=c["lavender"]),
        hl("SpecialChar", fg=c["lavender"]),
        hl("Delimiter", fg=c["muted"]),
        hl("SpecialComment", fg=c["comment"]),
        hl("Debug", fg=c["warning"]),
        hl("Underlined", fg=c["diagnostic"], underline=True),
        hl("Ignore", fg=bg),
        hl("Error", fg=c["error"]),
        hl("Todo", fg=c["warning"], bold=True),
        "",
        "  -- ── Treesitter ────────────────────────────────────────",
        hl("@variable", fg=c["muted"]),
        hl("@variable.builtin", fg=c["lavender"]),
        hl("@variable.parameter", fg=c["mauve"]),
        hl("@variable.member", fg=c["muted"]),
        hl("@constant", fg=c["mauve"]),
        hl("@constant.builtin", fg=c["lavender"]),
        hl("@constant.macro", fg=c["accent"]),
        hl("@module", fg=c["diagnostic"]),
        hl("@module.builtin", fg=c["accent"]),
        hl("@label", fg=c["accent_2"]),
        hl("@string", fg=c["sage"]),
        hl("@string.documentation", fg=c["sage"], italic=True),
        hl("@string.regex", fg=c["warning"]),
        hl("@string.escape", fg=c["warning"]),
        hl("@character", fg=c["sage"]),
        hl("@character.special", fg=c["lavender"]),
        hl("@number", fg=c["mauve"]),
        hl("@boolean", fg=c["lavender"]),
        hl("@float", fg=c["mauve"]),
        hl("@function", fg=c["accent_2"]),
        hl("@function.builtin", fg=c["accent_2"], bold=True),
        hl("@function.call", fg=c["accent_2"]),
        hl("@function.macro", fg=c["accent_2"]),
        hl("@function.method", fg=c["accent_2"]),
        hl("@function.method.call", fg=c["accent_2"]),
        hl("@parameter", fg=c["mauve"]),
        hl("@method", fg=c["accent_2"]),
        hl("@field", fg=c["diagnostic"]),
        hl("@property", fg=c["diagnostic"]),
        hl("@constructor", fg=c["accent"]),
        hl("@conditional", fg=c["accent"]),
        hl("@repeat", fg=c["accent"]),
        hl("@debug", fg=c["warning"]),
        hl("@include", fg=c["subtle"]),
        hl("@operator", fg=c["accent_2"]),
        hl("@keyword", fg=c["accent"]),
        hl("@keyword.function", fg=c["accent"], italic=True),
        hl("@keyword.operator", fg=c["accent_2"]),
        hl("@keyword.return", fg=c["accent"], bold=True),
        hl("@exception", fg=c["error"]),
        hl("@type", fg=c["diagnostic"]),
        hl("@type.builtin", fg=c["diagnostic"], bold=True),
        hl("@type.definition", fg=c["diagnostic"]),
        hl("@type.qualifier", fg=c["accent"]),
        hl("@storageclass", fg=c["accent"]),
        hl("@attribute", fg=c["subtle"]),
        hl("@symbol", fg=c["lavender"]),
        hl("@punctuation.delimiter", fg=c["muted"]),
        hl("@punctuation.bracket", fg=c["muted"]),
        hl("@punctuation.special", fg=c["lavender"]),
        hl("@comment", fg=c["comment"], italic=True),
        hl("@comment.error", fg=c["error"]),
        hl("@comment.warning", fg=c["warning"]),
        hl("@comment.todo", fg=c["warning"], bold=True),
        hl("@comment.note", fg=c["diagnostic"]),
    ]
