# ========================================================
# Dreamcoder Dark — Dunst theme
# ========================================================
# Include from dunstrc:
#   [include] dreamcoder-dunst.conf

[urgency_low]
    background = "#000000"
    foreground = "#E2E8F0"
    highlight = "#A5B4FC"
    frame_color = "#68788F"

[urgency_normal]
    background = "#060608"
    foreground = "#E2E8F0"
    highlight = "#A5B4FC"
    frame_color = "#68788F"

[urgency_critical]
    background = "#4b2828"
    foreground = "#E2E8F0"
    highlight = "#FB8585"
    frame_color = "#FB8585"
