# Dreamcoder Dark Night — Lazygit theme
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

gui:
  theme:
    activeBorderColor:
      - "#a4afee" # accent
      - "bold"
    inactiveBorderColor:
      - "#6d7788" # border
    searchingActiveBorderColor:
      - "#9f8ce9" # accent-2
      - "bold"
    optionsTextColor:
      - "#62b9e2" # diagnostic
    selectedLineBgColor:
      - "#141418" # selection
    inactiveViewSelectedLineBgColor:
      - "#141418" # surface-2
    cherryPickedCommitFgColor:
      - "#62b9e2"
    cherryPickedCommitBgColor:
      - "#9f8ce9"
    markedBaseCommitFgColor:
      - "#62b9e2"
    markedBaseCommitBgColor:
      - "#a4afee"
    unstagedChangesColor:
      - "#e88484" # error
    defaultFgColor:
      - "#bcc7d5" # text
  authorColors:
        "#a4afee": "#000000"
        "#9f8ce9": "#000000"
        "#62b9e2": "#000000"
        "#43b48b": "#000000"
        "#b98beb": "#000000"
  showFileTree: true
  showRandomTip: false
  nerdFontsVersion: "3"
  sidePanelWidth: 0.3
  expandFocusedSidePanel: true
  mainPanelSplitMode: "flexible"
  language: "en"
git:
  diffRenderers:
    - colorArg: always
      command: delta --syntax-theme "Catppuccin Mocha" --paging=never
  merging:
    manualCommit: false
  skipHookPrefix: WIP
  autoFetch: true
  autoRefresh: true
  branchLogCmd: "git log --graph --pretty=format:'%C(#a4afee)%h%Creset -%C(#9f8ce9)%d%Creset %s %C(#a69ba6)(%cr) %C(#62b9e2)<%an>%Creset' --date=relative"
update:
  method: never
