-- ========================================================
-- Dreamcoder Neovim — thin layer over Gentleman.Dots
-- ========================================================
-- Gentleman.Dots owns ALL config (nodejs, lazy, keymaps, options).
-- Dreamcoder only applies the colorscheme on top.
-- Symlink: ~/.config/nvim/init.lua -> Nvim/.config/nvim/init.lua

-- Source Gentleman's complete init.lua (config.nodejs, config.lazy, etc.)
dofile(vim.fn.expand("$HOME") .. "/Gentleman.Dots/GentlemanNvim/nvim/init.lua")

-- Dreamcoder colorscheme — applied ON TOP of Gentleman's defaults.
-- Generated by dreamcoder sync from tokens.json.
-- Variants: dark, light, dusk (mode-tracked via colors/dreamcoder.lua)
vim.cmd.colorscheme("dreamcoder")
