-- ========================================================
-- Dreamcoder Neovim — colorscheme registration
-- ========================================================
-- Registers Dreamcoder as an available LazyVim colorscheme.
-- The actual theme file is at colors/dreamcoder.lua
-- (generated by dreamcoder sync from tokens.json).

return {
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "dreamcoder",
    },
  },
}
