cursor #221a14
cursor_text_color #51443b

foreground            #221a14
background            #fff8f5
selection_foreground  #ffffff
selection_background  #e3c0a6
url_color             #89511f

# black
color8   #221a14
color0   #4c4c4c

# red
color1   #ba1a1a
color9   #c49ea0

# green
color2   #221a14
color10  #9ec49f

# yellow
color3   #aca98a
color11  #c4c19e

# blue
/* color4  #8f8aac */
color4  #89511f
color12 #a39ec4

# magenta
color5   #ba1a1a
color13  #c49ec4

# cyan
color6   #221a14
color14  #9ec3c4

# white
color15   #e7e7e7
color7  #f0f0f0