cursor #eee0d5
cursor_text_color #d5c3b5

foreground            #eee0d5
background            #19120c
selection_foreground  #feddbe
selection_background  #58432c
url_color             #fbb974

# black
color0   #302921
color8   #9d8e81

# red
color1   #ffb4ab
color9   #ffb4ab

# green
color2   #e1c1a3
color10  #e1c1a3

# yellow
color3   #bfcc9b
color11  #bfcc9b

# blue
color4   #fbb974
color12  #fbb974

# magenta
color5   #bfcc9b
color13  #bfcc9b

# cyan
color6   #e1c1a3
color14  #e1c1a3

# white
color7   #eee0d5
color15  #e7e7e7
