# ========================================================
# Dreamcoder Ember Noir OLED — Dunst theme
# ========================================================
# Include from dunstrc:
#   [include] dreamcoder-dunst.conf

[urgency_low]
    background = "#12100e"
    foreground = "#e8dfd0"
    highlight = "#d99555"
    frame_color = "#756052"

[urgency_normal]
    background = "#28201a"
    foreground = "#e8dfd0"
    highlight = "#d99555"
    frame_color = "#968878"

[urgency_critical]
    background = "#52322c"
    foreground = "#e8dfd0"
    highlight = "#e98272"
    frame_color = "#e98272"
