# ========================================================
# Dreamcoder Ember Noir — Dunst theme
# ========================================================
# Include from dunstrc:
#   [include] dreamcoder-dunst.conf

[urgency_low]
    background = "#14110e"
    foreground = "#f0e7dc"
    highlight = "#cdae7d"
    frame_color = "#594d46"

[urgency_normal]
    background = "#231c18"
    foreground = "#f0e7dc"
    highlight = "#cdae7d"
    frame_color = "#806754"

[urgency_critical]
    background = "#54332c"
    foreground = "#f0e7dc"
    highlight = "#e98272"
    frame_color = "#e98272"
