# ========================================================
# Dreamcoder Ember Noir — Dunst theme
# ========================================================
# Include from dunstrc:
#   [include] dreamcoder-dunst.conf

[urgency_low]
    background = "#12100e"
    foreground = "#e8dfd0"
    highlight = "#d99555"
    frame_color = "#594d46"

[urgency_normal]
    background = "#211c18"
    foreground = "#e8dfd0"
    highlight = "#d99555"
    frame_color = "#806754"

[urgency_critical]
    background = "#55322b"
    foreground = "#e8dfd0"
    highlight = "#e98272"
    frame_color = "#e98272"
