# ========================================================
# Dreamcoder Ember Noir — Dunst theme
# ========================================================
# Include from dunstrc:
#   [include] dreamcoder-dunst.conf

[urgency_low]
    background = "#15100d"
    foreground = "#f0e7dc"
    highlight = "#e6a15c"
    frame_color = "#49362c"

[urgency_normal]
    background = "#241b16"
    foreground = "#f0e7dc"
    highlight = "#e6a15c"
    frame_color = "#806754"

[urgency_critical]
    background = "#55322b"
    foreground = "#f0e7dc"
    highlight = "#e98272"
    frame_color = "#e98272"
