$background = rgba(12100eff)
$error = rgba(e98272ff)
$error_container = rgba(28201aff)
$inverse_on_surface = rgba(28201aff)
$inverse_primary = rgba(d99555ff)
$inverse_surface = rgba(e8dfd0ff)
$on_background = rgba(e8dfd0ff)
$on_error = rgba(12100eff)
$on_error_container = rgba(e8dfd0ff)
$on_primary = rgba(12100eff)
$on_primary_container = rgba(e8dfd0ff)
$on_primary_fixed = rgba(12100eff)
$on_primary_fixed_variant = rgba(d99555ff)
$on_secondary = rgba(12100eff)
$on_secondary_container = rgba(e8dfd0ff)
$on_secondary_fixed = rgba(12100eff)
$on_secondary_fixed_variant = rgba(c96a45ff)
$on_surface = rgba(e8dfd0ff)
$on_surface_variant = rgba(c7b9aaff)
$on_tertiary = rgba(12100eff)
$on_tertiary_container = rgba(e8dfd0ff)
$on_tertiary_fixed = rgba(12100eff)
$on_tertiary_fixed_variant = rgba(72b6bdff)
$outline = rgba(756052ff)
$outline_variant = rgba(968878ff)
$primary = rgba(d99555ff)
$primary_container = rgba(392b22ff)
$primary_fixed = rgba(d99555ff)
$primary_fixed_dim = rgba(c96a45ff)
$scrim = rgba(000000ff)
$secondary = rgba(c96a45ff)
$secondary_container = rgba(392b22ff)
$secondary_fixed = rgba(c96a45ff)
$secondary_fixed_dim = rgba(c96a45ff)
$shadow = rgba(000000ff)
$source_color = rgba(d99555ff)
$surface = rgba(12100eff)
$surface_bright = rgba(28201aff)
$surface_container = rgba(392b22ff)
$surface_container_high = rgba(392b22ff)
$surface_container_highest = rgba(4d3b2dff)
$surface_container_low = rgba(28201aff)
$surface_container_lowest = rgba(28201aff)
$surface_dim = rgba(1b1612ff)
$surface_tint = rgba(d99555ff)
$surface_variant = rgba(392b22ff)
$tertiary = rgba(5f95caff)
$tertiary_container = rgba(28201aff)
$tertiary_fixed = rgba(5f95caff)
$tertiary_fixed_dim = rgba(5f95caff)
