$background = rgba(f3eadcff)
$error = rgba(842f24ff)
$error_container = rgba(fff7eaff)
$inverse_on_surface = rgba(fff7eaff)
$inverse_primary = rgba(824f16ff)
$inverse_surface = rgba(17120dff)
$on_background = rgba(17120dff)
$on_error = rgba(f3eadcff)
$on_error_container = rgba(17120dff)
$on_primary = rgba(f3eadcff)
$on_primary_container = rgba(17120dff)
$on_primary_fixed = rgba(f3eadcff)
$on_primary_fixed_variant = rgba(824f16ff)
$on_secondary = rgba(f3eadcff)
$on_secondary_container = rgba(17120dff)
$on_secondary_fixed = rgba(f3eadcff)
$on_secondary_fixed_variant = rgba(a7471cff)
$on_surface = rgba(17120dff)
$on_surface_variant = rgba(352e22ff)
$on_tertiary = rgba(f3eadcff)
$on_tertiary_container = rgba(17120dff)
$on_tertiary_fixed = rgba(f3eadcff)
$on_tertiary_fixed_variant = rgba(0f6570ff)
$outline = rgba(7a6550ff)
$outline_variant = rgba(66513bff)
$primary = rgba(824f16ff)
$primary_container = rgba(decbb1ff)
$primary_fixed = rgba(824f16ff)
$primary_fixed_dim = rgba(a7471cff)
$scrim = rgba(000000ff)
$secondary = rgba(a7471cff)
$secondary_container = rgba(decbb1ff)
$secondary_fixed = rgba(a7471cff)
$secondary_fixed_dim = rgba(a7471cff)
$shadow = rgba(000000ff)
$source_color = rgba(824f16ff)
$surface = rgba(f3eadcff)
$surface_bright = rgba(fff7eaff)
$surface_container = rgba(decbb1ff)
$surface_container_high = rgba(decbb1ff)
$surface_container_highest = rgba(c8ad89ff)
$surface_container_low = rgba(fff7eaff)
$surface_container_lowest = rgba(fff7eaff)
$surface_dim = rgba(e6d7c4ff)
$surface_tint = rgba(824f16ff)
$surface_variant = rgba(decbb1ff)
$tertiary = rgba(0d4a68ff)
$tertiary_container = rgba(fff7eaff)
$tertiary_fixed = rgba(0d4a68ff)
$tertiary_fixed_dim = rgba(0d4a68ff)
