-- ========================================================
-- Dreamcoder Ember Noir — generated by Dreamcoder sync
-- ========================================================
-- Usage: vim.cmd.colorscheme("dreamcoder")
-- ========================================================

vim.g.colors_name = "dreamcoder"

-- Glass blur: transparent background + subtle float transparency
vim.opt.winblend = 10
vim.opt.pumblend = 10

local c = {
  bg        = "#12100e",
  surface0  = "#231c18",
  surface1  = "#2e241f",
  surface2  = "#3e3129",
  text      = "#f0e7dc",
  muted     = "#b8a99a",
  subtle    = "#9a8b7c",
  comment   = "#8c7c6d",
  accent    = "#d99555",
  accent2   = "#c96a45",
  diagnostic = "#c8b2a2",
  sage      = "#b8bf84",
  lavender  = "#c9a8dc",
  mauve     = "#d98aa9",
  error     = "#e98272",
  warning   = "#e8b866",
  border    = "#594d46",
  border_ui = "#806754",
  selection = "#373027",
}

local function h(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end

-- ── Editor UI ────────────────────────────────────────────────
-- Normal background = "none" for glass blur effect.
-- Terminal (Kitty/Ghostty) handles transparency + blur.

  vim.api.nvim_set_hl(0, "Normal", {
    fg = "#f0e7dc",
    bg = "none"
  })

  vim.api.nvim_set_hl(0, "NormalFloat", {
    fg = "#f0e7dc",
    bg = "#231c18"
  })

  vim.api.nvim_set_hl(0, "FloatBorder", {
    fg = "#806754",
    bg = "#231c18"
  })

  vim.api.nvim_set_hl(0, "NonText", {
    fg = "#9a8b7c"
  })

  vim.api.nvim_set_hl(0, "SpecialKey", {
    fg = "#b8a99a"
  })

  vim.api.nvim_set_hl(0, "Whitespace", {
    fg = "#594d46"
  })

  vim.api.nvim_set_hl(0, "EndOfBuffer", {
    fg = "none"
  })

  vim.api.nvim_set_hl(0, "Cursor", {
    fg = "#12100e",
    bg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "lCursor", {
    fg = "#12100e",
    bg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "CursorLine", {
    bg = "#231c18"
  })

  vim.api.nvim_set_hl(0, "CursorLineNr", {
    fg = "#d99555",
    bold = true
  })

  vim.api.nvim_set_hl(0, "LineNr", {
    fg = "#b8a99a"
  })

  vim.api.nvim_set_hl(0, "CursorColumn", {
    bg = "#231c18"
  })

  vim.api.nvim_set_hl(0, "ColorColumn", {
    bg = "#231c18"
  })

  vim.api.nvim_set_hl(0, "SignColumn", {
    bg = "none"
  })


  -- ── Selection & Search ───────────────────────────────
  vim.api.nvim_set_hl(0, "Visual", {
    fg = "#f0e7dc",
    bg = "#373027"
  })

  vim.api.nvim_set_hl(0, "VisualNOS", {
    fg = "#f0e7dc",
    bg = "#373027"
  })

  vim.api.nvim_set_hl(0, "Search", {
    fg = "#12100e",
    bg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "IncSearch", {
    fg = "#12100e",
    bg = "#c96a45"
  })

  vim.api.nvim_set_hl(0, "CurSearch", {
    fg = "#12100e",
    bg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "Substitute", {
    fg = "#12100e",
    bg = "#c96a45"
  })

  vim.api.nvim_set_hl(0, "MatchParen", {
    fg = "#c96a45",
    bold = true
  })


  -- ── Popup Menu ────────────────────────────────────────
  vim.api.nvim_set_hl(0, "Pmenu", {
    fg = "#b8a99a",
    bg = "#2e241f"
  })

  vim.api.nvim_set_hl(0, "PmenuSel", {
    fg = "#12100e",
    bg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "PmenuSbar", {
    bg = "#3e3129"
  })

  vim.api.nvim_set_hl(0, "PmenuThumb", {
    bg = "#b8a99a"
  })


  -- ── Statusline & Winbar ───────────────────────────────
  vim.api.nvim_set_hl(0, "StatusLine", {
    fg = "#f0e7dc",
    bg = "#2e241f"
  })

  vim.api.nvim_set_hl(0, "StatusLineNC", {
    fg = "#b8a99a",
    bg = "#231c18"
  })

  vim.api.nvim_set_hl(0, "StatusLineTerm", {
    fg = "#f0e7dc",
    bg = "#2e241f"
  })

  vim.api.nvim_set_hl(0, "StatusLineTermNC", {
    fg = "#b8a99a",
    bg = "#231c18"
  })

  vim.api.nvim_set_hl(0, "WinBar", {
    fg = "#f0e7dc",
    bg = "#2e241f"
  })

  vim.api.nvim_set_hl(0, "WinBarNC", {
    fg = "#b8a99a",
    bg = "#231c18"
  })

  vim.api.nvim_set_hl(0, "WinSeparator", {
    fg = "#594d46"
  })


  -- ── Tabline ────────────────────────────────────────────
  vim.api.nvim_set_hl(0, "TabLine", {
    fg = "#b8a99a",
    bg = "#231c18"
  })

  vim.api.nvim_set_hl(0, "TabLineSel", {
    fg = "#f0e7dc",
    bg = "#2e241f"
  })

  vim.api.nvim_set_hl(0, "TabLineFill", {
    bg = "#12100e"
  })


  -- ── Folds ─────────────────────────────────────────────
  vim.api.nvim_set_hl(0, "Folded", {
    fg = "#b8a99a",
    bg = "#231c18"
  })

  vim.api.nvim_set_hl(0, "FoldColumn", {
    fg = "#b8a99a"
  })


  -- ── Diff ──────────────────────────────────────────────
  vim.api.nvim_set_hl(0, "DiffAdd", {
    bg = "#504d38"
  })

  vim.api.nvim_set_hl(0, "DiffChange", {
    bg = "#5e4b2f"
  })

  vim.api.nvim_set_hl(0, "DiffDelete", {
    bg = "#5e3b33"
  })

  vim.api.nvim_set_hl(0, "DiffText", {
    bg = "#674b30"
  })


  -- ── Spell ─────────────────────────────────────────────
  vim.api.nvim_set_hl(0, "SpellBad", {
    sp = "#e98272",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "SpellCap", {
    sp = "#e8b866",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "SpellLocal", {
    sp = "#c8b2a2",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "SpellRare", {
    sp = "#d98aa9",
    undercurl = true
  })


  -- ── Messages ──────────────────────────────────────────
  vim.api.nvim_set_hl(0, "MsgArea", {
    fg = "#f0e7dc"
  })

  vim.api.nvim_set_hl(0, "ModeMsg", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "WarningMsg", {
    fg = "#e8b866"
  })

  vim.api.nvim_set_hl(0, "ErrorMsg", {
    fg = "#e98272"
  })

  vim.api.nvim_set_hl(0, "Question", {
    fg = "#c8b2a2"
  })


  -- ── Misc ──────────────────────────────────────────────
  vim.api.nvim_set_hl(0, "Title", {
    fg = "#d99555",
    bold = true
  })

  vim.api.nvim_set_hl(0, "Directory", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "Conceal", {
    fg = "#b8a99a"
  })

  vim.api.nvim_set_hl(0, "TermCursor", {
    fg = "#12100e",
    bg = "#d99555"
  })


  -- ── Classic Syntax ────────────────────────────────────
  vim.api.nvim_set_hl(0, "Comment", {
    fg = "#8c7c6d",
    italic = true
  })

  vim.api.nvim_set_hl(0, "Constant", {
    fg = "#d98aa9"
  })

  vim.api.nvim_set_hl(0, "String", {
    fg = "#b8bf84"
  })

  vim.api.nvim_set_hl(0, "Character", {
    fg = "#b8bf84"
  })

  vim.api.nvim_set_hl(0, "Number", {
    fg = "#d98aa9"
  })

  vim.api.nvim_set_hl(0, "Boolean", {
    fg = "#c9a8dc"
  })

  vim.api.nvim_set_hl(0, "Float", {
    fg = "#d98aa9"
  })

  vim.api.nvim_set_hl(0, "Identifier", {
    fg = "#f0e7dc"
  })

  vim.api.nvim_set_hl(0, "Function", {
    fg = "#c96a45"
  })

  vim.api.nvim_set_hl(0, "Statement", {
    fg = "#d99555",
    bold = true
  })

  vim.api.nvim_set_hl(0, "Conditional", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "Repeat", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "Label", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "Operator", {
    fg = "#c96a45"
  })

  vim.api.nvim_set_hl(0, "Keyword", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "Exception", {
    fg = "#e98272"
  })

  vim.api.nvim_set_hl(0, "PreProc", {
    fg = "#9a8b7c"
  })

  vim.api.nvim_set_hl(0, "Include", {
    fg = "#9a8b7c"
  })

  vim.api.nvim_set_hl(0, "Define", {
    fg = "#9a8b7c"
  })

  vim.api.nvim_set_hl(0, "PreCondit", {
    fg = "#9a8b7c"
  })

  vim.api.nvim_set_hl(0, "Type", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "StorageClass", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "Structure", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "Typedef", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "Special", {
    fg = "#c9a8dc"
  })

  vim.api.nvim_set_hl(0, "SpecialChar", {
    fg = "#c9a8dc"
  })

  vim.api.nvim_set_hl(0, "Delimiter", {
    fg = "#b8a99a"
  })

  vim.api.nvim_set_hl(0, "SpecialComment", {
    fg = "#8c7c6d"
  })

  vim.api.nvim_set_hl(0, "Debug", {
    fg = "#e8b866"
  })

  vim.api.nvim_set_hl(0, "Underlined", {
    fg = "#c8b2a2",
    underline = true
  })

  vim.api.nvim_set_hl(0, "Ignore", {
    fg = "#12100e"
  })

  vim.api.nvim_set_hl(0, "Error", {
    fg = "#e98272"
  })

  vim.api.nvim_set_hl(0, "Todo", {
    fg = "#e8b866",
    bold = true
  })


  -- ── Treesitter ────────────────────────────────────────
  vim.api.nvim_set_hl(0, "@variable", {
    fg = "#f0e7dc"
  })

  vim.api.nvim_set_hl(0, "@variable.builtin", {
    fg = "#c9a8dc"
  })

  vim.api.nvim_set_hl(0, "@variable.parameter", {
    fg = "#d98aa9"
  })

  vim.api.nvim_set_hl(0, "@variable.member", {
    fg = "#f0e7dc"
  })

  vim.api.nvim_set_hl(0, "@constant", {
    fg = "#d98aa9"
  })

  vim.api.nvim_set_hl(0, "@constant.builtin", {
    fg = "#c9a8dc"
  })

  vim.api.nvim_set_hl(0, "@constant.macro", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "@module", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "@module.builtin", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "@label", {
    fg = "#c96a45"
  })

  vim.api.nvim_set_hl(0, "@string", {
    fg = "#b8bf84"
  })

  vim.api.nvim_set_hl(0, "@string.documentation", {
    fg = "#b8bf84",
    italic = true
  })

  vim.api.nvim_set_hl(0, "@string.regex", {
    fg = "#c96a45"
  })

  vim.api.nvim_set_hl(0, "@string.escape", {
    fg = "#c96a45"
  })

  vim.api.nvim_set_hl(0, "@character", {
    fg = "#b8bf84"
  })

  vim.api.nvim_set_hl(0, "@character.special", {
    fg = "#c9a8dc"
  })

  vim.api.nvim_set_hl(0, "@number", {
    fg = "#d98aa9"
  })

  vim.api.nvim_set_hl(0, "@boolean", {
    fg = "#c9a8dc"
  })

  vim.api.nvim_set_hl(0, "@float", {
    fg = "#d98aa9"
  })

  vim.api.nvim_set_hl(0, "@function", {
    fg = "#c96a45"
  })

  vim.api.nvim_set_hl(0, "@function.builtin", {
    fg = "#c96a45",
    bold = true
  })

  vim.api.nvim_set_hl(0, "@function.call", {
    fg = "#c96a45"
  })

  vim.api.nvim_set_hl(0, "@function.macro", {
    fg = "#c96a45"
  })

  vim.api.nvim_set_hl(0, "@function.method", {
    fg = "#c96a45"
  })

  vim.api.nvim_set_hl(0, "@function.method.call", {
    fg = "#c96a45"
  })

  vim.api.nvim_set_hl(0, "@parameter", {
    fg = "#d98aa9"
  })

  vim.api.nvim_set_hl(0, "@method", {
    fg = "#c96a45"
  })

  vim.api.nvim_set_hl(0, "@field", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "@property", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "@constructor", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "@conditional", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "@repeat", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "@debug", {
    fg = "#e8b866"
  })

  vim.api.nvim_set_hl(0, "@include", {
    fg = "#9a8b7c"
  })

  vim.api.nvim_set_hl(0, "@operator", {
    fg = "#c96a45"
  })

  vim.api.nvim_set_hl(0, "@keyword", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "@keyword.function", {
    fg = "#d99555",
    italic = true
  })

  vim.api.nvim_set_hl(0, "@keyword.operator", {
    fg = "#c96a45"
  })

  vim.api.nvim_set_hl(0, "@keyword.return", {
    fg = "#d99555",
    bold = true
  })

  vim.api.nvim_set_hl(0, "@exception", {
    fg = "#e98272"
  })

  vim.api.nvim_set_hl(0, "@type", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "@type.builtin", {
    fg = "#c8b2a2",
    bold = true
  })

  vim.api.nvim_set_hl(0, "@type.definition", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "@type.qualifier", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "@storageclass", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "@attribute", {
    fg = "#9a8b7c"
  })

  vim.api.nvim_set_hl(0, "@symbol", {
    fg = "#c9a8dc"
  })

  vim.api.nvim_set_hl(0, "@punctuation.delimiter", {
    fg = "#b8a99a"
  })

  vim.api.nvim_set_hl(0, "@punctuation.bracket", {
    fg = "#b8a99a"
  })

  vim.api.nvim_set_hl(0, "@punctuation.special", {
    fg = "#c9a8dc"
  })

  vim.api.nvim_set_hl(0, "@comment", {
    fg = "#8c7c6d",
    italic = true
  })

  vim.api.nvim_set_hl(0, "@comment.error", {
    fg = "#e98272"
  })

  vim.api.nvim_set_hl(0, "@comment.warning", {
    fg = "#e8b866"
  })

  vim.api.nvim_set_hl(0, "@comment.todo", {
    fg = "#e8b866",
    bold = true
  })

  vim.api.nvim_set_hl(0, "@comment.note", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "@markup.strong", {
    bold = true
  })

  vim.api.nvim_set_hl(0, "@markup.italic", {
    italic = true
  })

  vim.api.nvim_set_hl(0, "@markup.strikethrough", {
    strikethrough = true
  })

  vim.api.nvim_set_hl(0, "@markup.underline", {
    underline = true
  })

  vim.api.nvim_set_hl(0, "@markup.heading", {
    fg = "#d99555",
    bold = true
  })

  vim.api.nvim_set_hl(0, "@markup.quote", {
    fg = "#8c7c6d",
    italic = true
  })

  vim.api.nvim_set_hl(0, "@markup.math", {
    fg = "#c9a8dc"
  })

  vim.api.nvim_set_hl(0, "@markup.link", {
    fg = "#c8b2a2",
    underline = true
  })

  vim.api.nvim_set_hl(0, "@markup.link.label", {
    fg = "#c8b2a2",
    underline = true
  })

  vim.api.nvim_set_hl(0, "@markup.link.url", {
    fg = "#9a8b7c",
    underline = true
  })

  vim.api.nvim_set_hl(0, "@markup.raw", {
    fg = "#b8bf84"
  })

  vim.api.nvim_set_hl(0, "@markup.list", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "@diff.plus", {
    fg = "#b8bf84"
  })

  vim.api.nvim_set_hl(0, "@diff.minus", {
    fg = "#e98272"
  })

  vim.api.nvim_set_hl(0, "@diff.delta", {
    fg = "#e8b866"
  })

  vim.api.nvim_set_hl(0, "@tag", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "@tag.attribute", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "@tag.delimiter", {
    fg = "#b8a99a"
  })


  -- ── LSP / Diagnostics ────────────────────────────────
  vim.api.nvim_set_hl(0, "DiagnosticError", {
    fg = "#e98272"
  })

  vim.api.nvim_set_hl(0, "DiagnosticWarn", {
    fg = "#e8b866"
  })

  vim.api.nvim_set_hl(0, "DiagnosticInfo", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "DiagnosticHint", {
    fg = "#c9a8dc"
  })

  vim.api.nvim_set_hl(0, "DiagnosticOk", {
    fg = "#b8bf84"
  })

  vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", {
    sp = "#e98272",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", {
    sp = "#e8b866",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", {
    sp = "#c8b2a2",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", {
    sp = "#c9a8dc",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", {
    fg = "#e98272"
  })

  vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", {
    fg = "#e8b866"
  })

  vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", {
    fg = "#c9a8dc"
  })

  vim.api.nvim_set_hl(0, "DiagnosticFloatingError", {
    fg = "#e98272"
  })

  vim.api.nvim_set_hl(0, "DiagnosticFloatingWarn", {
    fg = "#e8b866"
  })

  vim.api.nvim_set_hl(0, "DiagnosticFloatingInfo", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "DiagnosticFloatingHint", {
    fg = "#c9a8dc"
  })

  vim.api.nvim_set_hl(0, "DiagnosticSignError", {
    fg = "#e98272"
  })

  vim.api.nvim_set_hl(0, "DiagnosticSignWarn", {
    fg = "#e8b866"
  })

  vim.api.nvim_set_hl(0, "DiagnosticSignInfo", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "DiagnosticSignHint", {
    fg = "#c9a8dc"
  })

  vim.api.nvim_set_hl(0, "LspReferenceText", {
    bg = "#2e241f"
  })

  vim.api.nvim_set_hl(0, "LspReferenceRead", {
    bg = "#2e241f"
  })

  vim.api.nvim_set_hl(0, "LspReferenceWrite", {
    bg = "#2e241f"
  })

  vim.api.nvim_set_hl(0, "LspInlayHint", {
    fg = "#8c7c6d",
    bg = "#231c18"
  })


  -- ── Telescope ─────────────────────────────────────────
  vim.api.nvim_set_hl(0, "TelescopeNormal", {
    fg = "#f0e7dc",
    bg = "#12100e"
  })

  vim.api.nvim_set_hl(0, "TelescopeBorder", {
    fg = "#806754",
    bg = "#12100e"
  })

  vim.api.nvim_set_hl(0, "TelescopeTitle", {
    fg = "#d99555",
    bold = true
  })

  vim.api.nvim_set_hl(0, "TelescopePromptNormal", {
    fg = "#f0e7dc",
    bg = "#231c18"
  })

  vim.api.nvim_set_hl(0, "TelescopePromptBorder", {
    fg = "#806754",
    bg = "#231c18"
  })

  vim.api.nvim_set_hl(0, "TelescopePromptTitle", {
    fg = "#c96a45",
    bold = true
  })

  vim.api.nvim_set_hl(0, "TelescopeSelection", {
    fg = "#f0e7dc",
    bg = "#373027"
  })

  vim.api.nvim_set_hl(0, "TelescopeMultiSelection", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "TelescopeMatching", {
    fg = "#d99555",
    bold = true
  })

  vim.api.nvim_set_hl(0, "TelescopePreviewNormal", {
    fg = "#f0e7dc",
    bg = "#231c18"
  })

  vim.api.nvim_set_hl(0, "TelescopePreviewBorder", {
    fg = "#806754",
    bg = "#231c18"
  })

  vim.api.nvim_set_hl(0, "TelescopeResultsNormal", {
    fg = "#f0e7dc",
    bg = "#12100e"
  })

  vim.api.nvim_set_hl(0, "TelescopeResultsBorder", {
    fg = "#806754",
    bg = "#12100e"
  })


  -- ── NvimTree ─────────────────────────────────────────
  vim.api.nvim_set_hl(0, "NvimTreeNormal", {
    fg = "#f0e7dc",
    bg = "#12100e"
  })

  vim.api.nvim_set_hl(0, "NvimTreeRootFolder", {
    fg = "#d99555",
    bold = true
  })

  vim.api.nvim_set_hl(0, "NvimTreeGitDirty", {
    fg = "#e8b866"
  })

  vim.api.nvim_set_hl(0, "NvimTreeGitNew", {
    fg = "#b8bf84"
  })

  vim.api.nvim_set_hl(0, "NvimTreeGitDeleted", {
    fg = "#e98272"
  })

  vim.api.nvim_set_hl(0, "NvimTreeOpenedFile", {
    fg = "#c96a45"
  })

  vim.api.nvim_set_hl(0, "NvimTreeSpecialFile", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "NvimTreeSymlink", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "NvimTreeFolderName", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "NvimTreeFolderIcon", {
    fg = "#b8a99a"
  })

  vim.api.nvim_set_hl(0, "NvimTreeEmptyFolderName", {
    fg = "#b8a99a"
  })

  vim.api.nvim_set_hl(0, "NvimTreeOpenedFolderName", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "NvimTreeImageFile", {
    fg = "#c9a8dc"
  })

  vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", {
    fg = "#594d46"
  })

  vim.api.nvim_set_hl(0, "NvimTreeWinSeparator", {
    fg = "#806754",
    bg = "#12100e"
  })

  vim.api.nvim_set_hl(0, "NvimTreeCursorLine", {
    bg = "#231c18"
  })


  -- ── WhichKey ─────────────────────────────────────────
  vim.api.nvim_set_hl(0, "WhichKey", {
    fg = "#d99555",
    bold = true
  })

  vim.api.nvim_set_hl(0, "WhichKeyGroup", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "WhichKeyDesc", {
    fg = "#f0e7dc"
  })

  vim.api.nvim_set_hl(0, "WhichKeySeperator", {
    fg = "#b8a99a"
  })

  vim.api.nvim_set_hl(0, "WhichKeySeparator", {
    fg = "#b8a99a"
  })

  vim.api.nvim_set_hl(0, "WhichKeyFloat", {
    fg = "#f0e7dc",
    bg = "#231c18"
  })

  vim.api.nvim_set_hl(0, "WhichKeyBorder", {
    fg = "#806754"
  })

  vim.api.nvim_set_hl(0, "WhichKeyValue", {
    fg = "#d98aa9"
  })


  -- ── Lazy / Noice / Cmp ───────────────────────────────
  vim.api.nvim_set_hl(0, "LazyNormal", {
    fg = "#f0e7dc",
    bg = "#12100e"
  })

  vim.api.nvim_set_hl(0, "LazyReasonPlugin", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "LazyReasonStart", {
    fg = "#b8bf84"
  })

  vim.api.nvim_set_hl(0, "LazyReasonSource", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "LazyReasonRt", {
    fg = "#d98aa9"
  })

  vim.api.nvim_set_hl(0, "LazyReasonCmd", {
    fg = "#c9a8dc"
  })

  vim.api.nvim_set_hl(0, "LazyValue", {
    fg = "#d98aa9"
  })

  vim.api.nvim_set_hl(0, "LazyCommit", {
    fg = "#b8bf84"
  })

  vim.api.nvim_set_hl(0, "LazySpecial", {
    fg = "#c9a8dc"
  })

  vim.api.nvim_set_hl(0, "LazyDir", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "LazyH1", {
    fg = "#d99555",
    bold = true
  })

  vim.api.nvim_set_hl(0, "LazyButton", {
    fg = "#f0e7dc",
    bg = "#2e241f"
  })

  vim.api.nvim_set_hl(0, "LazyButtonActive", {
    fg = "#12100e",
    bg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "NoiceMsg", {
    fg = "#f0e7dc"
  })

  vim.api.nvim_set_hl(0, "NoiceCursor", {
    fg = "#12100e",
    bg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "MiniCompletionActiveParameter", {
    underline = true
  })

  vim.api.nvim_set_hl(0, "CmpItemAbbr", {
    fg = "#f0e7dc"
  })

  vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", {
    fg = "#d99555",
    bold = true
  })

  vim.api.nvim_set_hl(0, "CmpItemAbbrMatchFuzzy", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "CmpItemKind", {
    fg = "#b8a99a"
  })

  vim.api.nvim_set_hl(0, "CmpItemMenu", {
    fg = "#b8a99a"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindSnippet", {
    fg = "#d98aa9"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindKeyword", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindText", {
    fg = "#f0e7dc"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindMethod", {
    fg = "#c96a45"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindFunction", {
    fg = "#c96a45"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindConstructor", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindField", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindVariable", {
    fg = "#d98aa9"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindClass", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindInterface", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindModule", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindProperty", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindUnit", {
    fg = "#b8bf84"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindValue", {
    fg = "#d98aa9"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindEnum", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindEnumMember", {
    fg = "#d98aa9"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindKeyword", {
    fg = "#d99555"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindColor", {
    fg = "#c9a8dc"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindFile", {
    fg = "#f0e7dc"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindReference", {
    fg = "#c96a45"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindFolder", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindEvent", {
    fg = "#e8b866"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindOperator", {
    fg = "#c96a45"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindTypeParameter", {
    fg = "#c8b2a2"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindCopied", {
    fg = "#b8bf84"
  })

