-- ========================================================
-- Dreamcoder Dusk — generated by Dreamcoder sync
-- ========================================================
-- Usage: vim.cmd.colorscheme("dreamcoder")
-- ========================================================

vim.g.colors_name = "dreamcoder"

-- Glass blur stays dark-only; light/dusk need opaque paper backgrounds for readability.
vim.opt.winblend = 10
vim.opt.pumblend = 10

local c = {
  bg        = "#ebe4d6",
  surface0  = "#f1eadf",
  surface1  = "#d8cbb8",
  surface2  = "#c6b6a0",
  text      = "#1a1713",
  muted     = "#4c443a",
  subtle    = "#5a4f43",
  comment   = "#615548",
  accent    = "#8a5520",
  accent2   = "#96411e",
  diagnostic = "#104b67",
  sage      = "#466b41",
  lavender  = "#5b4e86",
  mauve     = "#784762",
  error     = "#773126",
  warning   = "#604000",
  border    = "#a7947a",
  border_ui = "#665845",
  selection = "#d8cbb8",
}

local function h(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end

-- ── Editor UI ────────────────────────────────────────────────
-- Normal background is opaque in light/dusk so dark terminal transparency cannot hide text.
-- Dark mode keeps transparent Normal for Ember Noir glass.

  vim.api.nvim_set_hl(0, "Normal", {
    fg = "#1a1713",
    bg = "#ebe4d6"
  })

  vim.api.nvim_set_hl(0, "NormalFloat", {
    fg = "#1a1713",
    bg = "#f1eadf"
  })

  vim.api.nvim_set_hl(0, "FloatBorder", {
    fg = "#665845",
    bg = "#f1eadf"
  })

  vim.api.nvim_set_hl(0, "NonText", {
    fg = "#5a4f43"
  })

  vim.api.nvim_set_hl(0, "SpecialKey", {
    fg = "#4c443a"
  })

  vim.api.nvim_set_hl(0, "Whitespace", {
    fg = "#a7947a"
  })

  vim.api.nvim_set_hl(0, "EndOfBuffer", {
    fg = "none"
  })

  vim.api.nvim_set_hl(0, "Cursor", {
    fg = "#ebe4d6",
    bg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "lCursor", {
    fg = "#ebe4d6",
    bg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "CursorLine", {
    bg = "#f1eadf"
  })

  vim.api.nvim_set_hl(0, "CursorLineNr", {
    fg = "#8a5520",
    bold = true
  })

  vim.api.nvim_set_hl(0, "LineNr", {
    fg = "#4c443a"
  })

  vim.api.nvim_set_hl(0, "CursorColumn", {
    bg = "#f1eadf"
  })

  vim.api.nvim_set_hl(0, "ColorColumn", {
    bg = "#f1eadf"
  })

  vim.api.nvim_set_hl(0, "SignColumn", {
    bg = "#ebe4d6"
  })


  -- ── Selection & Search ───────────────────────────────
  vim.api.nvim_set_hl(0, "Visual", {
    fg = "#1a1713",
    bg = "#d8cbb8"
  })

  vim.api.nvim_set_hl(0, "VisualNOS", {
    fg = "#1a1713",
    bg = "#d8cbb8"
  })

  vim.api.nvim_set_hl(0, "Search", {
    fg = "#ebe4d6",
    bg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "IncSearch", {
    fg = "#ebe4d6",
    bg = "#96411e"
  })

  vim.api.nvim_set_hl(0, "CurSearch", {
    fg = "#ebe4d6",
    bg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "Substitute", {
    fg = "#ebe4d6",
    bg = "#96411e"
  })

  vim.api.nvim_set_hl(0, "MatchParen", {
    fg = "#96411e",
    bold = true
  })


  -- ── Popup Menu ────────────────────────────────────────
  vim.api.nvim_set_hl(0, "Pmenu", {
    fg = "#4c443a",
    bg = "#d8cbb8"
  })

  vim.api.nvim_set_hl(0, "PmenuSel", {
    fg = "#ebe4d6",
    bg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "PmenuSbar", {
    bg = "#c6b6a0"
  })

  vim.api.nvim_set_hl(0, "PmenuThumb", {
    bg = "#4c443a"
  })


  -- ── Statusline & Winbar ───────────────────────────────
  vim.api.nvim_set_hl(0, "StatusLine", {
    fg = "#1a1713",
    bg = "#d8cbb8"
  })

  vim.api.nvim_set_hl(0, "StatusLineNC", {
    fg = "#4c443a",
    bg = "#f1eadf"
  })

  vim.api.nvim_set_hl(0, "StatusLineTerm", {
    fg = "#1a1713",
    bg = "#d8cbb8"
  })

  vim.api.nvim_set_hl(0, "StatusLineTermNC", {
    fg = "#4c443a",
    bg = "#f1eadf"
  })

  vim.api.nvim_set_hl(0, "WinBar", {
    fg = "#1a1713",
    bg = "#d8cbb8"
  })

  vim.api.nvim_set_hl(0, "WinBarNC", {
    fg = "#4c443a",
    bg = "#f1eadf"
  })

  vim.api.nvim_set_hl(0, "WinSeparator", {
    fg = "#a7947a"
  })


  -- ── Tabline ────────────────────────────────────────────
  vim.api.nvim_set_hl(0, "TabLine", {
    fg = "#4c443a",
    bg = "#f1eadf"
  })

  vim.api.nvim_set_hl(0, "TabLineSel", {
    fg = "#1a1713",
    bg = "#d8cbb8"
  })

  vim.api.nvim_set_hl(0, "TabLineFill", {
    bg = "#ebe4d6"
  })


  -- ── Folds ─────────────────────────────────────────────
  vim.api.nvim_set_hl(0, "Folded", {
    fg = "#4c443a",
    bg = "#f1eadf"
  })

  vim.api.nvim_set_hl(0, "FoldColumn", {
    fg = "#4c443a"
  })


  -- ── Diff ──────────────────────────────────────────────
  vim.api.nvim_set_hl(0, "DiffAdd", {
    bg = "#bec4b0"
  })

  vim.api.nvim_set_hl(0, "DiffChange", {
    bg = "#c6b79c"
  })

  vim.api.nvim_set_hl(0, "DiffDelete", {
    bg = "#ccb2a8"
  })

  vim.api.nvim_set_hl(0, "DiffText", {
    bg = "#a8bdb9"
  })


  -- ── Spell ─────────────────────────────────────────────
  vim.api.nvim_set_hl(0, "SpellBad", {
    sp = "#773126",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "SpellCap", {
    sp = "#604000",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "SpellLocal", {
    sp = "#104b67",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "SpellRare", {
    sp = "#784762",
    undercurl = true
  })


  -- ── Messages ──────────────────────────────────────────
  vim.api.nvim_set_hl(0, "MsgArea", {
    fg = "#1a1713"
  })

  vim.api.nvim_set_hl(0, "ModeMsg", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "WarningMsg", {
    fg = "#604000"
  })

  vim.api.nvim_set_hl(0, "ErrorMsg", {
    fg = "#773126"
  })

  vim.api.nvim_set_hl(0, "Question", {
    fg = "#104b67"
  })


  -- ── Misc ──────────────────────────────────────────────
  vim.api.nvim_set_hl(0, "Title", {
    fg = "#8a5520",
    bold = true
  })

  vim.api.nvim_set_hl(0, "Directory", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "Conceal", {
    fg = "#4c443a"
  })

  vim.api.nvim_set_hl(0, "TermCursor", {
    fg = "#ebe4d6",
    bg = "#8a5520"
  })


  -- ── Classic Syntax ────────────────────────────────────
  vim.api.nvim_set_hl(0, "Comment", {
    fg = "#615548",
    italic = true
  })

  vim.api.nvim_set_hl(0, "Constant", {
    fg = "#784762"
  })

  vim.api.nvim_set_hl(0, "String", {
    fg = "#466b41"
  })

  vim.api.nvim_set_hl(0, "Character", {
    fg = "#466b41"
  })

  vim.api.nvim_set_hl(0, "Number", {
    fg = "#784762"
  })

  vim.api.nvim_set_hl(0, "Boolean", {
    fg = "#5b4e86"
  })

  vim.api.nvim_set_hl(0, "Float", {
    fg = "#784762"
  })

  vim.api.nvim_set_hl(0, "Identifier", {
    fg = "#1a1713"
  })

  vim.api.nvim_set_hl(0, "Function", {
    fg = "#96411e"
  })

  vim.api.nvim_set_hl(0, "Statement", {
    fg = "#8a5520",
    bold = true
  })

  vim.api.nvim_set_hl(0, "Conditional", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "Repeat", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "Label", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "Operator", {
    fg = "#96411e"
  })

  vim.api.nvim_set_hl(0, "Keyword", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "Exception", {
    fg = "#773126"
  })

  vim.api.nvim_set_hl(0, "PreProc", {
    fg = "#5a4f43"
  })

  vim.api.nvim_set_hl(0, "Include", {
    fg = "#5a4f43"
  })

  vim.api.nvim_set_hl(0, "Define", {
    fg = "#5a4f43"
  })

  vim.api.nvim_set_hl(0, "PreCondit", {
    fg = "#5a4f43"
  })

  vim.api.nvim_set_hl(0, "Type", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "StorageClass", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "Structure", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "Typedef", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "Special", {
    fg = "#5b4e86"
  })

  vim.api.nvim_set_hl(0, "SpecialChar", {
    fg = "#5b4e86"
  })

  vim.api.nvim_set_hl(0, "Delimiter", {
    fg = "#4c443a"
  })

  vim.api.nvim_set_hl(0, "SpecialComment", {
    fg = "#615548"
  })

  vim.api.nvim_set_hl(0, "Debug", {
    fg = "#604000"
  })

  vim.api.nvim_set_hl(0, "Underlined", {
    fg = "#104b67",
    underline = true
  })

  vim.api.nvim_set_hl(0, "Ignore", {
    fg = "#ebe4d6"
  })

  vim.api.nvim_set_hl(0, "Error", {
    fg = "#773126"
  })

  vim.api.nvim_set_hl(0, "Todo", {
    fg = "#604000",
    bold = true
  })


  -- ── Treesitter ────────────────────────────────────────
  vim.api.nvim_set_hl(0, "@variable", {
    fg = "#1a1713"
  })

  vim.api.nvim_set_hl(0, "@variable.builtin", {
    fg = "#5b4e86"
  })

  vim.api.nvim_set_hl(0, "@variable.parameter", {
    fg = "#784762"
  })

  vim.api.nvim_set_hl(0, "@variable.member", {
    fg = "#1a1713"
  })

  vim.api.nvim_set_hl(0, "@constant", {
    fg = "#784762"
  })

  vim.api.nvim_set_hl(0, "@constant.builtin", {
    fg = "#5b4e86"
  })

  vim.api.nvim_set_hl(0, "@constant.macro", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "@module", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "@module.builtin", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "@label", {
    fg = "#96411e"
  })

  vim.api.nvim_set_hl(0, "@string", {
    fg = "#466b41"
  })

  vim.api.nvim_set_hl(0, "@string.documentation", {
    fg = "#466b41",
    italic = true
  })

  vim.api.nvim_set_hl(0, "@string.regex", {
    fg = "#96411e"
  })

  vim.api.nvim_set_hl(0, "@string.escape", {
    fg = "#96411e"
  })

  vim.api.nvim_set_hl(0, "@character", {
    fg = "#466b41"
  })

  vim.api.nvim_set_hl(0, "@character.special", {
    fg = "#5b4e86"
  })

  vim.api.nvim_set_hl(0, "@number", {
    fg = "#784762"
  })

  vim.api.nvim_set_hl(0, "@boolean", {
    fg = "#5b4e86"
  })

  vim.api.nvim_set_hl(0, "@float", {
    fg = "#784762"
  })

  vim.api.nvim_set_hl(0, "@function", {
    fg = "#96411e"
  })

  vim.api.nvim_set_hl(0, "@function.builtin", {
    fg = "#96411e",
    bold = true
  })

  vim.api.nvim_set_hl(0, "@function.call", {
    fg = "#96411e"
  })

  vim.api.nvim_set_hl(0, "@function.macro", {
    fg = "#96411e"
  })

  vim.api.nvim_set_hl(0, "@function.method", {
    fg = "#96411e"
  })

  vim.api.nvim_set_hl(0, "@function.method.call", {
    fg = "#96411e"
  })

  vim.api.nvim_set_hl(0, "@parameter", {
    fg = "#784762"
  })

  vim.api.nvim_set_hl(0, "@method", {
    fg = "#96411e"
  })

  vim.api.nvim_set_hl(0, "@field", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "@property", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "@constructor", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "@conditional", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "@repeat", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "@debug", {
    fg = "#604000"
  })

  vim.api.nvim_set_hl(0, "@include", {
    fg = "#5a4f43"
  })

  vim.api.nvim_set_hl(0, "@operator", {
    fg = "#96411e"
  })

  vim.api.nvim_set_hl(0, "@keyword", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "@keyword.function", {
    fg = "#8a5520",
    italic = true
  })

  vim.api.nvim_set_hl(0, "@keyword.operator", {
    fg = "#96411e"
  })

  vim.api.nvim_set_hl(0, "@keyword.return", {
    fg = "#8a5520",
    bold = true
  })

  vim.api.nvim_set_hl(0, "@exception", {
    fg = "#773126"
  })

  vim.api.nvim_set_hl(0, "@type", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "@type.builtin", {
    fg = "#104b67",
    bold = true
  })

  vim.api.nvim_set_hl(0, "@type.definition", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "@type.qualifier", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "@storageclass", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "@attribute", {
    fg = "#5a4f43"
  })

  vim.api.nvim_set_hl(0, "@symbol", {
    fg = "#5b4e86"
  })

  vim.api.nvim_set_hl(0, "@punctuation.delimiter", {
    fg = "#4c443a"
  })

  vim.api.nvim_set_hl(0, "@punctuation.bracket", {
    fg = "#4c443a"
  })

  vim.api.nvim_set_hl(0, "@punctuation.special", {
    fg = "#5b4e86"
  })

  vim.api.nvim_set_hl(0, "@comment", {
    fg = "#615548",
    italic = true
  })

  vim.api.nvim_set_hl(0, "@comment.error", {
    fg = "#773126"
  })

  vim.api.nvim_set_hl(0, "@comment.warning", {
    fg = "#604000"
  })

  vim.api.nvim_set_hl(0, "@comment.todo", {
    fg = "#604000",
    bold = true
  })

  vim.api.nvim_set_hl(0, "@comment.note", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "@markup.strong", {
    bold = true
  })

  vim.api.nvim_set_hl(0, "@markup.italic", {
    italic = true
  })

  vim.api.nvim_set_hl(0, "@markup.strikethrough", {
    strikethrough = true
  })

  vim.api.nvim_set_hl(0, "@markup.underline", {
    underline = true
  })

  vim.api.nvim_set_hl(0, "@markup.heading", {
    fg = "#8a5520",
    bold = true
  })

  vim.api.nvim_set_hl(0, "@markup.quote", {
    fg = "#615548",
    italic = true
  })

  vim.api.nvim_set_hl(0, "@markup.math", {
    fg = "#5b4e86"
  })

  vim.api.nvim_set_hl(0, "@markup.link", {
    fg = "#104b67",
    underline = true
  })

  vim.api.nvim_set_hl(0, "@markup.link.label", {
    fg = "#104b67",
    underline = true
  })

  vim.api.nvim_set_hl(0, "@markup.link.url", {
    fg = "#5a4f43",
    underline = true
  })

  vim.api.nvim_set_hl(0, "@markup.raw", {
    fg = "#466b41"
  })

  vim.api.nvim_set_hl(0, "@markup.list", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "@diff.plus", {
    fg = "#466b41"
  })

  vim.api.nvim_set_hl(0, "@diff.minus", {
    fg = "#773126"
  })

  vim.api.nvim_set_hl(0, "@diff.delta", {
    fg = "#604000"
  })

  vim.api.nvim_set_hl(0, "@tag", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "@tag.attribute", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "@tag.delimiter", {
    fg = "#4c443a"
  })


  -- ── LSP / Diagnostics ────────────────────────────────
  vim.api.nvim_set_hl(0, "DiagnosticError", {
    fg = "#773126"
  })

  vim.api.nvim_set_hl(0, "DiagnosticWarn", {
    fg = "#604000"
  })

  vim.api.nvim_set_hl(0, "DiagnosticInfo", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "DiagnosticHint", {
    fg = "#5b4e86"
  })

  vim.api.nvim_set_hl(0, "DiagnosticOk", {
    fg = "#466b41"
  })

  vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", {
    sp = "#773126",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", {
    sp = "#604000",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", {
    sp = "#104b67",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", {
    sp = "#5b4e86",
    undercurl = true
  })

  vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", {
    fg = "#773126"
  })

  vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", {
    fg = "#604000"
  })

  vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", {
    fg = "#5b4e86"
  })

  vim.api.nvim_set_hl(0, "DiagnosticFloatingError", {
    fg = "#773126"
  })

  vim.api.nvim_set_hl(0, "DiagnosticFloatingWarn", {
    fg = "#604000"
  })

  vim.api.nvim_set_hl(0, "DiagnosticFloatingInfo", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "DiagnosticFloatingHint", {
    fg = "#5b4e86"
  })

  vim.api.nvim_set_hl(0, "DiagnosticSignError", {
    fg = "#773126"
  })

  vim.api.nvim_set_hl(0, "DiagnosticSignWarn", {
    fg = "#604000"
  })

  vim.api.nvim_set_hl(0, "DiagnosticSignInfo", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "DiagnosticSignHint", {
    fg = "#5b4e86"
  })

  vim.api.nvim_set_hl(0, "LspReferenceText", {
    bg = "#d8cbb8"
  })

  vim.api.nvim_set_hl(0, "LspReferenceRead", {
    bg = "#d8cbb8"
  })

  vim.api.nvim_set_hl(0, "LspReferenceWrite", {
    bg = "#d8cbb8"
  })

  vim.api.nvim_set_hl(0, "LspInlayHint", {
    fg = "#615548",
    bg = "#f1eadf"
  })


  -- ── Telescope ─────────────────────────────────────────
  vim.api.nvim_set_hl(0, "TelescopeNormal", {
    fg = "#1a1713",
    bg = "#ebe4d6"
  })

  vim.api.nvim_set_hl(0, "TelescopeBorder", {
    fg = "#665845",
    bg = "#ebe4d6"
  })

  vim.api.nvim_set_hl(0, "TelescopeTitle", {
    fg = "#8a5520",
    bold = true
  })

  vim.api.nvim_set_hl(0, "TelescopePromptNormal", {
    fg = "#1a1713",
    bg = "#f1eadf"
  })

  vim.api.nvim_set_hl(0, "TelescopePromptBorder", {
    fg = "#665845",
    bg = "#f1eadf"
  })

  vim.api.nvim_set_hl(0, "TelescopePromptTitle", {
    fg = "#96411e",
    bold = true
  })

  vim.api.nvim_set_hl(0, "TelescopeSelection", {
    fg = "#1a1713",
    bg = "#d8cbb8"
  })

  vim.api.nvim_set_hl(0, "TelescopeMultiSelection", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "TelescopeMatching", {
    fg = "#8a5520",
    bold = true
  })

  vim.api.nvim_set_hl(0, "TelescopePreviewNormal", {
    fg = "#1a1713",
    bg = "#f1eadf"
  })

  vim.api.nvim_set_hl(0, "TelescopePreviewBorder", {
    fg = "#665845",
    bg = "#f1eadf"
  })

  vim.api.nvim_set_hl(0, "TelescopeResultsNormal", {
    fg = "#1a1713",
    bg = "#ebe4d6"
  })

  vim.api.nvim_set_hl(0, "TelescopeResultsBorder", {
    fg = "#665845",
    bg = "#ebe4d6"
  })


  -- ── NvimTree ─────────────────────────────────────────
  vim.api.nvim_set_hl(0, "NvimTreeNormal", {
    fg = "#1a1713",
    bg = "#ebe4d6"
  })

  vim.api.nvim_set_hl(0, "NvimTreeRootFolder", {
    fg = "#8a5520",
    bold = true
  })

  vim.api.nvim_set_hl(0, "NvimTreeGitDirty", {
    fg = "#604000"
  })

  vim.api.nvim_set_hl(0, "NvimTreeGitNew", {
    fg = "#466b41"
  })

  vim.api.nvim_set_hl(0, "NvimTreeGitDeleted", {
    fg = "#773126"
  })

  vim.api.nvim_set_hl(0, "NvimTreeOpenedFile", {
    fg = "#96411e"
  })

  vim.api.nvim_set_hl(0, "NvimTreeSpecialFile", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "NvimTreeSymlink", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "NvimTreeFolderName", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "NvimTreeFolderIcon", {
    fg = "#4c443a"
  })

  vim.api.nvim_set_hl(0, "NvimTreeEmptyFolderName", {
    fg = "#4c443a"
  })

  vim.api.nvim_set_hl(0, "NvimTreeOpenedFolderName", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "NvimTreeImageFile", {
    fg = "#5b4e86"
  })

  vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", {
    fg = "#a7947a"
  })

  vim.api.nvim_set_hl(0, "NvimTreeWinSeparator", {
    fg = "#665845",
    bg = "#ebe4d6"
  })

  vim.api.nvim_set_hl(0, "NvimTreeCursorLine", {
    bg = "#f1eadf"
  })


  -- ── WhichKey ─────────────────────────────────────────
  vim.api.nvim_set_hl(0, "WhichKey", {
    fg = "#8a5520",
    bold = true
  })

  vim.api.nvim_set_hl(0, "WhichKeyGroup", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "WhichKeyDesc", {
    fg = "#1a1713"
  })

  vim.api.nvim_set_hl(0, "WhichKeySeperator", {
    fg = "#4c443a"
  })

  vim.api.nvim_set_hl(0, "WhichKeySeparator", {
    fg = "#4c443a"
  })

  vim.api.nvim_set_hl(0, "WhichKeyFloat", {
    fg = "#1a1713",
    bg = "#f1eadf"
  })

  vim.api.nvim_set_hl(0, "WhichKeyBorder", {
    fg = "#665845"
  })

  vim.api.nvim_set_hl(0, "WhichKeyValue", {
    fg = "#784762"
  })


  -- ── Lazy / Noice / Cmp ───────────────────────────────
  vim.api.nvim_set_hl(0, "LazyNormal", {
    fg = "#1a1713",
    bg = "#ebe4d6"
  })

  vim.api.nvim_set_hl(0, "LazyReasonPlugin", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "LazyReasonStart", {
    fg = "#466b41"
  })

  vim.api.nvim_set_hl(0, "LazyReasonSource", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "LazyReasonRt", {
    fg = "#784762"
  })

  vim.api.nvim_set_hl(0, "LazyReasonCmd", {
    fg = "#5b4e86"
  })

  vim.api.nvim_set_hl(0, "LazyValue", {
    fg = "#784762"
  })

  vim.api.nvim_set_hl(0, "LazyCommit", {
    fg = "#466b41"
  })

  vim.api.nvim_set_hl(0, "LazySpecial", {
    fg = "#5b4e86"
  })

  vim.api.nvim_set_hl(0, "LazyDir", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "LazyH1", {
    fg = "#8a5520",
    bold = true
  })

  vim.api.nvim_set_hl(0, "LazyButton", {
    fg = "#1a1713",
    bg = "#d8cbb8"
  })

  vim.api.nvim_set_hl(0, "LazyButtonActive", {
    fg = "#ebe4d6",
    bg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "NoiceMsg", {
    fg = "#1a1713"
  })

  vim.api.nvim_set_hl(0, "NoiceCursor", {
    fg = "#ebe4d6",
    bg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "MiniCompletionActiveParameter", {
    underline = true
  })

  vim.api.nvim_set_hl(0, "CmpItemAbbr", {
    fg = "#1a1713"
  })

  vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", {
    fg = "#8a5520",
    bold = true
  })

  vim.api.nvim_set_hl(0, "CmpItemAbbrMatchFuzzy", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "CmpItemKind", {
    fg = "#4c443a"
  })

  vim.api.nvim_set_hl(0, "CmpItemMenu", {
    fg = "#4c443a"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindSnippet", {
    fg = "#784762"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindKeyword", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindText", {
    fg = "#1a1713"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindMethod", {
    fg = "#96411e"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindFunction", {
    fg = "#96411e"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindConstructor", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindField", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindVariable", {
    fg = "#784762"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindClass", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindInterface", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindModule", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindProperty", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindUnit", {
    fg = "#466b41"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindValue", {
    fg = "#784762"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindEnum", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindEnumMember", {
    fg = "#784762"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindKeyword", {
    fg = "#8a5520"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindColor", {
    fg = "#5b4e86"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindFile", {
    fg = "#1a1713"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindReference", {
    fg = "#96411e"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindFolder", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindEvent", {
    fg = "#604000"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindOperator", {
    fg = "#96411e"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindTypeParameter", {
    fg = "#104b67"
  })

  vim.api.nvim_set_hl(0, "CmpItemKindCopied", {
    fg = "#466b41"
  })

